### ISSUE TITLE
[BUG] Load dataType-test-pk/test_tinytext.sql failed

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1071]
**Describe the bug**
ERROR SharedSQLContext: Load dataType-test-pk/test_tinytext.sql failed. Maybe the file does not exist or has syntax error.

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/56/pipeline/738

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tispark_regression_test_daily/runs/56/nodes/738/log/?start=0

INFO SharedSQLContext: generate data is enabled and seed is 1566940913381

**Comment by zhexuany** [comment]
[2019-08-27T21:22:24.713Z] 19/08/28 05:22:24 ERROR SharedSQLContext: Load dataType-test-pk/test_tinytext.sql failed. Maybe the file does not exist or has syntax error.

From Jekins, this looks suspicious. I will spend some time in it.

**Comment by birdstorm** [comment]
Closes by #1259
