### ISSUE TITLE
org.apache.spark.sql.TiContext  cannot be applied to (org.apache.spark.sql.SparkSession) 

### ISSUE THREAD

**Issue by Satangel** [pingcap/tispark#109]
When I using the TiSpark's example to run spark, I get some errors .

`scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
<console>:24: error: overloaded method constructor TiContext with alternatives:
  (session: org.apache.spark.sql.SparkSession,addressList: java.util.List[String])org.apache.spark.sql.TiContext <and>
  (session: org.apache.spark.sql.SparkSession,addressList: scala.collection.immutable.List[String])org.apache.spark.sql.TiContext
 cannot be applied to (org.apache.spark.sql.SparkSession)
       val ti = new TiContext(spark)
                ^`
My TiSpark is installed by default, why it has alternatives?

**Comment by ilovesoup** [comment]
It looks like you are using very old version of TiSpark. Would you please let us know where you got the jar? @Satangel

**Comment by Satangel** [comment]
I used tidb-ansible's master branch to installed tidb on Nov 9 , when Tispark was installed by default.

**Comment by ilovesoup** [comment]
@Satangel you don't need to reinstall tidb. It's only TiSpark's jar is very old. You might try to build tispark itself.
1. run bin/build-client.sh
2. mvn clean package for tispark itself.

**Comment by birdstorm** [comment]
You may use the newest tidb-ansible's master branch to solve this problem. The jar package it used on Nov 9th was too old. @Satangel

**Comment by Satangel** [comment]
I used the newest tidb-ansible in github to reinstalled the tidb today , but the problem still exists. Is there any other way to solve the problem if the problem is tispark jar package is too old? @birdstorm

**Comment by ilovesoup** [comment]
@Satangel I tried link in ansible-master
http://download.pingcap.org/tispark-SNAPSHOT-jar-with-dependencies.jar
which should work. Please make sure existing jars purged if any. Further help if you need, send me a email at maxiaoyu@pingcap.com and we might communicate via IM which will be faster.

**Comment by birdstorm** [comment]
@ilovesoup the jar in this link does not work, it should be `http://download.pingcap.org/tispark-0.1.0-SNAPSHOT-jar-with-dependencies.jar`, I have pushed a PR to solve this.

@Satangel If your are urgent, you may change the url link `url: http://download.pingcap.org/tispark-SNAPSHOT-jar-with-dependencies.jar` to `url: http://download.pingcap.org/tispark-0.1.0-SNAPSHOT-jar-with-dependencies.jar` located in file `roles/local/templates/binary_packages.yml.j2` on line `44` manually. It should resolve the problem.

**Comment by Satangel** [comment]
@birdstorm wow, it worked.

**Comment by birdstorm** [comment]
@Satangel My pleasure.
