### ISSUE TITLE
[BUG] Maven build TiSpark

### ISSUE THREAD

**Issue by darionyaphet** [pingcap/tispark#1201]
When I build this repo by `mvn clean install -Dmaven.test.skip=true` and java version `1.8.0_201`.

```
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/TikvGrpc.java:[23,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/PDGrpc.java:[20,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/binlog/PumpGrpc.java:[23,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/ImportSSTGrpc.java:[35,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/binlog/CisternGrpc.java:[23,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/DebugGrpc.java:[30,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/ImportKVGrpc.java:[39,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/deadlock/DeadlockGrpc.java:[20,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/org/tikv/kvproto/BackupGrpc.java:[20,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/darion/repo/tispark/tikv-client/target/generated-sources/protobuf/grpc-java/enginepb/EngineGrpc.java:[20,18] 找不到符号
[ERROR]   符号:   类 Generated
[ERROR]   位置: 程序包 javax.annotation
```

**Comment by marsishandsome** [comment]
would you please check if there is a class  `javax.annotation.Generated` exits in `$JAVA_HOME/lib/rt.jar` ?

![image](https://user-images.githubusercontent.com/5574887/68643044-f5561680-054a-11ea-9ac0-8295c2b4d863.png)

**Comment by marsishandsome** [comment]
would please try this PR https://github.com/pingcap/tispark/pull/1202?

**Comment by birdstorm** [comment]
hi, @darionyaphet.

Please confirm that you are using Java 8 because TiSpark is incompatible with other Java versions. You should not need to add them explicitly.

**Comment by darionyaphet** [comment]
> hi, @darionyaphet.
> 
> Please confirm that you are using Java 8 because TiSpark is incompatible with other Java versions. You should not need to add `javax.annotation` explicitly.

Yep, Java version is `1.8.0_201`

**Comment by birdstorm** [comment]
> > hi, @darionyaphet.
> > Please confirm that you are using Java 8 because TiSpark is incompatible with other Java versions. You should not need to add `javax.annotation` explicitly.
> 
> Yep, Java version is `1.8.0_201`

Thanks, you may check if #1202 solves your problem.

**Comment by darionyaphet** [comment]
> > > hi, @darionyaphet.
> > > Please confirm that you are using Java 8 because TiSpark is incompatible with other Java versions. You should not need to add `javax.annotation` explicitly.
> > 
> > 
> > Yep, Java version is `1.8.0_201`
> 
> Thanks, you may check if #1202 solves your problem.

It's good point and have fixed. thanks ~

**Comment by zhexuany** [comment]
@darionyaphet I suspect you are using java 9 rather than java 8. Could you run `java -version` and share the result?

**Comment by darionyaphet** [comment]
```
~/repo/tispark(master*) » java -version                                                                                                                                                                                      darion@localhost
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

Sorry, It seems `JDK 8` & beyond  doubt.

**Comment by zhexuany** [comment]
It is related to https://github.com/pingcap/tispark/issues/1203. It seems `maven` is using java 11 rather java 8.
