### ISSUE TITLE
Support spark jdbc upsert

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1224]
https://www.jianshu.com/p/606a2dd62604

https://github.com/teeyog/IQL/tree/master/iql-spark-2.3-adaptor/src/main/java/org/apache/spark/sql/execution/datasources/jdbc2

https://www.jianshu.com/p/d0bac129a04c

**Comment by wfnuser** [comment]
I'll try to solve this.

**Comment by shiyuhang0** [comment]
TiSpark can upsert TiDB with options. As for JDBC, I don't think this is what TiSpark needs to do.

**Comment by shiyuhang0** [comment]
Can this issue be closed for we have supported upsert  of TiDB

**Comment by shiyuhang0** [comment]
closed becasue we can use tidb datasource to upsert.
