### ISSUE TITLE
use `df.isEmpty` insteadof `count`

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1228]
https://github.com/pingcap/tispark/blob/927cacf07c0c80fe3dedb5c6415cc790c4f9750d/core/src/main/scala/com/pingcap/tispark/TiBatchWrite.scala#L144

use `df.isEmpty` insteadof `count`

**Comment by wfnuser** [comment]
Let me try to solve this problem!

**Comment by wfnuser** [comment]
But I didn't find that Dataset has a method called isEmpty...

**Comment by birdstorm** [comment]
@wfnuser Thanks for you help! FYI, there is an `isEmpty` in `df.rdd`.

However you may need to cache it first to reduce duplicate operations, which is being done in PR #1158 . You may track this issue for its progress.

**Comment by wfnuser** [comment]
> @wfnuser Thanks for you help! FYI, there is an `isEmpty` in `df.rdd`.
> 
> However you may need to cache it first to reduce duplicate operations, which is being done in PR #1158 . You may track this issue for its progress.

I see. I will figure it out later...
