### ISSUE TITLE
support columnar batch execution with spark-3.0

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1264]
support columnar batch execution with spark-3.0
- in this PR https://github.com/pingcap/tispark/pull/1263
- or in this branch https://github.com/pingcap/tispark/tree/feature/support-spark-3.0-rebase-columnar

please use this profile `spark-3.0-scala-2.12` and uncomment the following code to enable test with spark-3.0

```
                    /*MVN_PROFILE_SCALA_2_12_TEST.each { MVN_TEST_PROFILE ->
                        sh """
                            export MAVEN_OPTS="-Xmx6G -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=51M"
                            mvn clean test ${MVN_PROFILE} ${MVN_PROFILE_SCALA_2_12} ${MVN_TEST_PROFILE} -Dtest=moo ${mvnStr}
                        """
                    }*/
```

see: https://github.com/apache/spark/pull/25008/files/8c285e57837bc1ccb87c0d894805ceb5d16f1299

**Comment by melin** [comment]
spark 3.0 发布了，准备启动支持吗？

**Comment by marsishandsome** [comment]
我们会尽快支持
