### ISSUE TITLE
Trying to use Elasticsearch with TiSpark - Any pointers or inputs would be helpful

### ISSUE THREAD

**Issue by diwakarpp** [pingcap/tispark#1268]
Hi,

Basically I am planning to replace TiSpark and connect other SQL or Analytical systems directly to DistSQL API.

Is there any example implementation or configuration references or docs so I would be able to hook up other systems through DistSQL API.

Thanks and regards,
Diwakar

**Comment by marsishandsome** [comment]
hi,

you can directly use https://github.com/pingcap/kvproto to call DistSQL API

**Comment by diwakarpp** [comment]
Hi,

Thank you very much for the kvproto reference. Its very helpful. Actually I was originally intending to ask about configuring TiSpark to use Elasticsearch as described in the page: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-installation

Is it possible to configure the TiSpark so it can save to Elasticsearch as described in the above link? This in turn enable me to use (Spark + Elasticsearch) + TiDB.

**Comment by marsishandsome** [comment]
`TiSpark` is an extension of spark. You can use any functionality provided by official spark or any third-party libraries.  Please let us know if you encounter any problems during writing data to ES.

**Comment by diwakarpp** [comment]
Hi, thank you very much. I will continue to work on it and will re-open this ticket if any help is needed. For now, closing this one.
