### ISSUE TITLE
Any doc or config references to use DistSQL API to replace TiSpark

### ISSUE THREAD

**Issue by diwakarpp** [pingcap/tispark#1269]
Hi,

Basically I am planning to replace TiSpark and connect other SQL or Analytical systems directly to DistSQL API.

Is there any example implementation or configuration references or docs so I would be able to hook up other systems through DistSQL API.

Thanks and regards,
Diwakar

**Comment by marsishandsome** [comment]
hi,

you can directly use https://github.com/pingcap/kvproto to call DistSQL API

**Comment by marsishandsome** [comment]
duplicate https://github.com/pingcap/tispark/issues/1268
