### ISSUE TITLE
If the hive databases and tables are the same as tidb databases and table，how does the TiSpark with Hive work

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tispark#1285]
How does the TiSpark with Hive work when hive databases and tables are the same as tidb databases and tables.

**Comment by marsishandsome** [comment]
`spark.tispark.db_prefix` can be used to solve this problem.
You can find the document in https://github.com/pingcap/tispark#configuration

**Comment by wfxxh** [comment]
@marsishandsome Thank you
