### ISSUE TITLE
support `in` pushdown

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1319]
support `in` pushdown in tispark (see chspark)

**Comment by wfnuser** [comment]
I would like to take a look😀
What is chspark? And can anyone provide some more details for this issue. @marsishandsome

**Comment by marsishandsome** [comment]
chspark is our internal version of TiSpark

**Comment by wfnuser** [comment]
So I won't be able to participate? 😔

**Comment by marsishandsome** [comment]
I will send you some documents if you are interested.

**Comment by wfnuser** [comment]
> I will send you some documents if you are interested.

Cool. I'm deeply interested.

**Comment by shiyuhang0** [comment]
colsed by repeated with https://github.com/pingcap/tispark/issues/1427
