### ISSUE TITLE
tidb3.0版本spark sql 不能读取tidb创建的视图

### ISSUE THREAD

**Issue by zhangpeng1990618** [pingcap/tispark#1329]
通过tispark 把hive 和tidb 表融入在一起，spark sql创建视图，视图sql可能只有tidb表，hive表，或者tidb和hive表同时存在，目前不支持tidb 表创建的视图，读取会报类型错误

**Comment by marsishandsome** [comment]
tispark目前确实不支持读取tidb的view

**Comment by birdstorm** [comment]
duplicate with #961
