### ISSUE TITLE
table with partition cannot be showed correctly in thrift-server 

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#1330]
spark 2.4.4 thrift server 通过spark.sql.extensions org.apache.spark.sql.TiExtens 添加tispark，执行一下语句：
```
show table extended like 'test_users_dt' PARTITION (ds ='20171011')
```
实际返回值为下面语句返回值，执行时丢失分区信息：
```
show table extended like 'test_users_dt' 
```
![image](https://user-images.githubusercontent.com/1145830/71390837-d748ff00-263c-11ea-81c0-8f58cae0c65d.png)

**Comment by zhexuany** [comment]
@melin Thanks for reporting. After some investigation, we already found the root cause. 

When we do `show tables`, we did not consider `partitioned table`. We will fix it as soon as possible.

**Comment by melin** [comment]
> @melin Thanks for reporting. After some investigation, we already found the root cause.
> 
> When we do `show tables`, we did not consider `partitioned table`. We will fix it as soon as possible.
大概什么时候可以修复

**Comment by marsishandsome** [comment]
@melin 请问这个问题在你们这里优先级高吗？

**Comment by melin** [comment]
> @melin 请问这个问题在你们这里优先级高吗？

比较高的，辛苦尽快修复一下

**Comment by zhexuany** [comment]
@melin 
Ok, We will fix it as soon as possible.

**Comment by zhexuany** [comment]
@melin could you tell us you are using hive partition table or tidb partition table?

**Comment by melin** [comment]
> @melin could you tell us you are using hive partition table or tidb partition table?

hive partition table

**Comment by zhexuany** [comment]
@melin gotcha. We will merge the PR in short future.
