### ISSUE TITLE
[BUG] Spark thriftserver memory leak

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#1378]
Spark thriftserver 运行了两年多了(只运行DDL语句)，一直都很正常，最近添加org.apache.spark.sql.TiExtens 以后。就会频繁重新，发现异常日志如下，取消配置以后，恢复正常，大概率与tispark 有关系。
![image](https://user-images.githubusercontent.com/1145830/72683059-fb4e1200-3b0e-11ea-8c2b-3b43db8606f3.png)

**Comment by birdstorm** [comment]
@melin Thanks for your report. Working on this.

**Comment by birdstorm** [comment]
Due to leak of TiContext creation.
