### ISSUE TITLE
[BUG]  DESC TABLE COLUMN throws NoSuchDatabaseException

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#1388]
**Describe the bug**
Tried to desc and check table info on a tispark / tidb table.

**What did you do**
`0: jdbc:hive2://whatever/chbenchmark> desc EXTENDED chbenchmark.nation n_nationkey;`

`Error: org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException: Database 'chbenchmark' not found; (state=,code=0)`

**What do you expect**
Should work as non tispark table.

**What happens instead**
Database name is not recognized.

**Spark and TiSpark version info**
Master via ThriftServer.

**Comment by birdstorm** [comment]
The issue is actually: desc column from table is not yet supported.
