### ISSUE TITLE
Could TiSpark provide Permission control mechanism for table

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tispark#1466]
**Describe the solution you'd like**
Could TiSpark provide Permission control mechanism for table

**Describe alternatives you've considered**
we use hadoop+tidb , any user could access all tidb tables ,it's not safe.

**Comment by marsishandsome** [comment]
TiSpark Permission Control is planned in TiDB-5.0 and probably will be available at the end of 2020.

**Comment by shiyuhang0** [comment]
closed by https://github.com/pingcap/tispark/pull/2185
