### ISSUE TITLE
[BUG] It doesn't fail when insert statement contains conflicting data and replace option is false

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1512]
**Describe the bug**

**What did you do**
1. create table in tidb
```sql
CREATE TABLE `t_pk_incr` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
)
```
2. register the tidb table t_pk_incr to spark catalog
```sql
CREATE TABLE t_pk_incr_tmp USING tidb OPTIONS (
  tidb.user 'root',
  tidb.password '',
  database 'test',
  table 't_pk_incr'
)
```
3. insert into t_pk_incr_tmp values (101,101),(101,101)

**What do you expect**

failed
**What happens instead**

success 

**Spark and TiSpark version info**

tispark: 2.3.0-rc.1
spark: spark-2.4.6-bin-hadoop2.7
tidb: 3.0.14

**Comment by birdstorm** [comment]
@lilinghai Thanks for your report! I will fix it.

**Comment by marsishandsome** [comment]
currently user provided auto increment value is only supported in update mode!
