### ISSUE TITLE
Single-node TiDB Docker image for testing

### ISSUE THREAD

**Issue by liancheng** [pingcap/tispark#152]
It would be great to have a testing Docker image that provides a single-node but complete TiDB environment so that people can add integration tests to TiSpark.

(This Docker image can also be useful for new users to try TiDB.)

**Comment by zhexuany** [comment]
@liancheng my colleague already wrote one. You can check https://github.com/tennix/tidb-docker-compose
It has some problems, me and my colleague are currently working on this.

**Comment by zhexuany** [comment]
Now, we can use docker-compose to provide tidb cluster service. Closing.
