### ISSUE TITLE
[BUG] The result of inserting into the column that is primary key and auto_increment using 0 is not correct

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1523]
**Describe the bug**

**What did you do**

1. create table t in tidb
```sql
create table t(a int auto_increment primary key);
```
2. write data to t using tispark
```scala
insert into t values(0)
```
3. select table t in tidb
```sql
select * from t;
```
**What do you expect**

1
**What happens instead**

0

**Spark and TiSpark version info**

tispark: 2.3.1
spark: spark-2.4.6-bin-hadoop2.7
tidb: v4.0.2

**Comment by birdstorm** [comment]
@lilinghai  Thanks for your report!

**Comment by marsishandsome** [comment]
tispark now disables `user provided auto increment value`
