### ISSUE TITLE
TiSpark针对TiDB分区表做查询时，如果指定分区字段筛选条件，TiSaprk不能够分区过滤，TiDB可以

### ISSUE THREAD

**Issue by Just-do-it-Fan** [pingcap/tispark#1591]
使用版本如下：
TiDB 4.0.4
TiSpark 2.4.0
Spark 2.3.1

建表语句如下：
CREATE TABLE quarterly_report_status (
    report_id INT NOT NULL,
    report_status VARCHAR(20) NOT NULL,
    report_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
PARTITION BY RANGE ( UNIX_TIMESTAMP(report_updated) ) (
    PARTITION p0 VALUES LESS THAN ( UNIX_TIMESTAMP('2020-07-01 00:00:00') ),
    PARTITION p1 VALUES LESS THAN ( UNIX_TIMESTAMP('2020-08-01 00:00:00') ),
    PARTITION p2 VALUES LESS THAN ( UNIX_TIMESTAMP('2020-09-01 00:00:00') ),
    PARTITION p3 VALUES LESS THAN (MAXVALUE)
);
测试数据：
insert into quarterly_report_status values (1,'a','2020-07-02 00:00:00'),(2,'b','2020-08-02 00:00:00'),(3,'c','2020-02-02 00:00:00');
查询sql：
select count(*) from db_yqs_p_94207_isrealtime.quarterly_report_status where report_updated='2020-07-02 00:00:00';

在TiSpark中的查询计划如下，虽然针对分区字段做了筛选条件，但是扫描所有分区的数据：
![image](https://user-images.githubusercontent.com/22441484/91546506-20ccb500-e955-11ea-9388-865d120a749b.png)
在TiDB中的查询计划如下，针对分区字段做了筛选条件后，命中了筛选的分区数据：
![image](https://user-images.githubusercontent.com/22441484/91546749-84ef7900-e955-11ea-80d0-da8e938f5144.png)

如果在TiSpark中的查询也可做到只扫筛选分区的数据，应该可以提升很多性能，并减少集群的负担

**Comment by birdstorm** [comment]
we will support UNIX_TIMESTAMP() function later.

**Comment by Just-do-it-Fan** [comment]
> we will support UNIX_TIMESTAMP() function later.
