### ISSUE TITLE
[BUG] Fail to batch write decimal type with conversion in new row format

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#1622]
**Describe the bug**
batch write with decimal type will fail when using new row format

**Spark and TiSpark version info**

**Comment by Dieken** [comment]
could you release v2.3.5 to maven repository? waiting for this fix, thanks!

**Comment by marsishandsome** [comment]
> could you release v2.3.5 to maven repository? waiting for this fix, thanks!
> 
> @birdstorm @marsishandsome

hi Dieken, v2.3.5 will be available tomorrow.

**Comment by marsishandsome** [comment]
@Dieken v2.3.5 is available now https://github.com/pingcap/tispark/releases/tag/v2.3.5
