### ISSUE TITLE
[BUG] can't select table when tispark write table in TiDB 4.0.1 with useTableLock=false

### ISSUE THREAD

**Issue by Dieken** [pingcap/tispark#1628]
**Describe the bug**

https://github.com/pingcap/tispark/blob/master/docs/datasource_api_userguide.md#tidb-options
```
useTableLock | false | true (3.x) false (4.x) | Whether to lock the table during writing
```

I set `useTableLock` to `false`, but `select * from test.t limit 10` still freeze when TiSpark is writing.

**What did you do**

```java
        Map<String, String> tidbOptions = new HashMap<>();
        tidbOptions.put("tidb.addr", config.getProperty("tidb.addr", "127.0.0.1").trim());
        tidbOptions.put("tidb.port", config.getProperty("tidb.port", "4000").trim());
        tidbOptions.put("tidb.user", config.getProperty("tidb.user", "root").trim());
        tidbOptions.put("tidb.password", config.getProperty("tidb.password", "").trim());
        tidbOptions.put("replace", "true");
        tidbOptions.put("useTableLock", "false");

             df.write()
                .format("tidb")
                .options(tidbOptions)
                .option("database", "test")
                .option("table", "t)
                .mode(SaveMode.Append)
                .save();
```

Run `select * from test.t limit 10` when the spark job is writing the table (I'm pretty sure it's writing tidb).

**What do you expect**

The select clause shouldn't freeze.

**What happens instead**

The select clause does freeze.

**Spark and TiSpark version info**

* TiDB: 5.7.25-TiDB-v4.0.1
* TiSpark: 2.3.4
* Spark: 2.4.7
* JDK: 1.8

**Comment by marsishandsome** [comment]
how many rows are there in table `test.t` before writing?

**Comment by marsishandsome** [comment]
would you please provide `tidb's log` during `The select clause does freeze` ?

**Comment by marsishandsome** [comment]
@Dieken i cannot reproduce this problem. would you please provide the script to reproduce this problem?
it will be nice if you can send your `WeChat` id to my email `guliangliang@pingcap.com`

**Comment by Dieken** [comment]
The destination table is empty,  about 30w rows take 150s to insert with TiSpark,  8 x 4C/32G spark executors.

Seems our TiKV nodes are overloaded,  after adding one more TiKV node, the insertion above takes about 40s,  the freeze time decreases to 2~10s,  don't know how many seconds it would take ago,  I interrupted the select clause because it's too slow.

Although the freeze time is still too large, it's probably related to busy TiKV node, not table lock, so I close this issue now.

**Comment by marsishandsome** [comment]
2~10s freeze time meets expectations. 
in this scenario, `tidb` needs to do something extra in order to solve the `read-write` conflict.
