### ISSUE TITLE
Optimize count(*) logic

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#167]
It is said from TiDB that certain optimization of push down columns could result in some performance improvement.

See https://github.com/pingcap/tidb/pull/5447

**Comment by birdstorm** [comment]
keep in mind that `count()` acts differently in mysql and spark.

**Comment by Novemser** [comment]
@birdstorm Shall you describe the differences here in details? Thanks.

**Comment by birdstorm** [comment]
@Novemser if you use `count()` in spark, the result is 0. It is different from `count(*)`.

**Comment by birdstorm** [comment]
@Novemser It seems that TiKV has now supported setting key_only flag in coprocessor/scanner since [pingcap/tikv#2580](https://github.com/pingcap/tikv/pull/2580/files), maybe we can take advantage with that.
