### ISSUE TITLE
Is there any tispark benchmark result ? 

### ISSUE THREAD

**Issue by yeyuqiang** [pingcap/tispark#168]
I've finished the deployment according the recommendation and success to run the TPCH query according the tispark doc. But it's based on a small data size. I try to comparing HDFS and TiKV as the data source of spark sql based on 500G data which generated by TPC-DS tool kit. But in my environment the TPC-DS benchmark result is not ideal. So is there any official tispark benchmark result to refer?

**Comment by Novemser** [comment]
Benchmark tests report is currently under construction, we will publish this in the near future. 

For now I recommend you trying tuning your TiKV (refer to https://github.com/pingcap/docs-cn/blob/master/op-guide/tune-tikv.md), and see if you could get any performance improvement. : )

**Comment by ilovesoup** [comment]
We had a brief test couple of month ago and not quite valid for current version anymore. And as my colleague said we will test it again before GA. 
Admittedly for workload like TPC-H and TPC-DS, which largely depend on pure scan speed, TiSpark is likely to be slower than static columnar file like Parquet. After all, the storage layer is optimized mostly for OLTP.  On the other hand, we expect cases that leveraging index out perform HDFS files and we are working on it.
In general, it is not designed to be a system faster than Spark on HDFS. It enables you analyze fresh data with reasonable speed. If you care speed most, TiSpark is likely not your answer (for now, we are working on new engine with columnar store).

**Comment by ilovesoup** [comment]
I will close this for now.
