### ISSUE TITLE
[BUG] The value of Date type column is not correct

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1685]
**Describe the bug**
The value of Date type column is not correct

**What did you do**

1. make the tidb and tispark have same time zone

2. execute in tidb
create table t(id varchar(11),b date)
insert into values(null,'2020-10-10')

3. execute in tispark
select * from t

**What do you expect**
null, '2020-10-10'

**What happens instead**
null, '2020-10-09'

**Spark and TiSpark version info**
Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by birdstorm** [comment]
Related to #1703

**Comment by birdstorm** [comment]
Closed by #1703
