### ISSUE TITLE
[BUG] Region not exist for key during rolling upgrade tikv cluster

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1689]
![image](https://user-images.githubusercontent.com/5574887/97379693-4e57bf80-1900-11eb-9fde-fbbf7394deaf.png)

![image](https://user-images.githubusercontent.com/5574887/97379791-8e1ea700-1900-11eb-8235-04abfde6b988.png)

tidb: 3.0.14
tispark: 2.0

**Comment by birdstorm** [comment]
TiSpark v2.0.x is not maintained anymore.
