### ISSUE TITLE
[BUG] The select statement with condition on year type column having index is not correct

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1692]
**Describe the bug**

The select statement with condition on year type column having index is not correct
**What did you do**

1. execute in tidb
create table t1(id varchar(10),a year,index(a))
insert into t1 values('ab',10)
insert into t1 values('ab',12)
insert into t1 values('ab',14)
insert into t1 values('ab',18)
2. execute in tispark
select * from t1 where a>2010 and a<2015
select * from t1 where a>12 and a<15

**What do you expect**

the result is not empty in select statement
**What happens instead**

empty result

**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by marsishandsome** [comment]
execute in tidb

```
mysql> select * from t1 where a>2010 and a<2015;
+------+------+
| id   | a    |
+------+------+
| ab   | 2012 |
| ab   | 2014 |
+------+------+
2 rows in set (0.05 sec)

mysql> select * from t1 where a>12 and a<15;
Empty set (0.04 sec)
```
