### ISSUE TITLE
[BUG] Insert null value into auto_increment or auto_random primary column raise “illegal null values” exception

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1744]
**Describe the bug**

Considering the testability Improvement and user habits in sql, can we support the feature of `Insert null value into auto_increment or auto_random primary column`? However now it will raise the exception of `illegal null values` when using insert statement above mentioned.
**What did you do**

1. execute in tidb
create table t(a biting primary key auto_random)
create table t2(a biting primary key auto_increment)
2. execute in tispark
insert into t values(null)
insert into t2 values(null)

**What do you expect**

success
**What happens instead**

```com.pingcap.tikv.exception.TiBatchWriteException: Insert null value to not null column! rows contain illegal null values!```
**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by marsishandsome** [comment]
insert null into `auto increment` column is supported now (https://github.com/pingcap/tispark/pull/1786).

**Comment by marsishandsome** [comment]
disable writing to table with `auto_random` column
https://github.com/pingcap/tispark/pull/1837
