### ISSUE TITLE
[BUG] It will raise the exception of "conflict primary key" when inserting into auto_random primary column 

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1745]
**Describe the bug**

It will raise the exception of "conflict primary key" when inserting into auto_random primary column.
**What did you do**

1. execute in tidb
create table t(a biting primary key auto_random,b int)
2. execute in tispark
```
for i in range(100):
    insert into t values({i},{I})
```
3. execute in tidb
```
for i in range(100):
    insert into t(b) values(1)
```
**What do you expect**

success
**What happens instead**

tidb raise ```Duplicate entry '37' for key 'PRIMARY'```
**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by marsishandsome** [comment]
should throw error
add to document

**Comment by marsishandsome** [comment]
writing to table with auto_random column is disable
https://github.com/pingcap/tispark/pull/1837
