### ISSUE TITLE
[BUG] The result of converting datetime or timestamp type to number type is not as expected

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1747]
**Describe the bug**

The result of converting datetime or timestamp type to number type is not as expected.
**What did you do**

1. execute in tidb
create table t1 (b datetime);
insert into t1(b) values ("2020-10-10")
2. execute in tispark
select cast(b as double) from t1

**What do you expect**

20200101000000
**What happens instead**

1602259200
**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by birdstorm** [comment]
TiSpark's result is correct according to SparkSQL.

```scala
spark.sql("select cast(timestamp'2020-10-10 00:00:00' as double)").show
+--------------------------------------------------+
|CAST(TIMESTAMP('2020-10-10 00:00:00.0') AS DOUBLE)|
+--------------------------------------------------+
|                                       1.6022592E9|
+--------------------------------------------------+
```
