### ISSUE TITLE
Priority is partially hardcoded

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#180]
<a href="https://github.com/ilovesoup"><img src="https://avatars2.githubusercontent.com/u/3347719?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ilovesoup](https://github.com/ilovesoup)**
_Mon Nov 27 17:25:00 2017_
_Originally opened as https://github.com/pingcap/tikv-client-lib-java/issues/159_

----

Command priority is partially hard coded for Region object.

**Comment by marsishandsome** [comment]
spark.tispark.request.command.priority
