### ISSUE TITLE
Downgrade to table scan if index read too many handle from individual region

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#184]
<a href="https://github.com/ilovesoup"><img src="https://avatars2.githubusercontent.com/u/3347719?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ilovesoup](https://github.com/ilovesoup)**
_Tue Dec  5 06:17:34 2017_
_Originally opened as https://github.com/pingcap/tikv-client-lib-java/issues/179_

----

If retrieves too many handles from an individual region, downgrade index scan to table scan. The threshold should be configurable.

**Comment by Novemser** [comment]
Fixed by #140
