### ISSUE TITLE
[BUG] load datetime value '0000-00-00 00:00:00' ,then tiSpark will get value not excpeted

### ISSUE THREAD

**Issue by RUIzg** [pingcap/tispark#1859]
**Describe the bug**
load datetime value '0000-00-00 00:00:00' ,then tiSpark will get value not excpeted

 
I use spark-sql to get datetime value   '0000-00-00 00:00:00'  from Tidb , 
then  get '0000-12-30 00:05:43' value ,but not   '0000-00-00 00:00:00' 
 
tidb version: 
Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

spark version:
  <spark.version>2.4.7</spark.version>
tispark-2.3.9

**Comment by marsishandsome** [comment]
would please run the following code?
```
spark.sql("select ti_version()").show(false)
```

**Comment by marsishandsome** [comment]
https://github.com/pingcap/tispark/issues/1701

**Comment by RUIzg** [comment]
|Release Version: 2.3.9
Git Commit Hash: 9ba472f0e63281888398c2d5de69114545616906
Git Branch: release-2.3
UTC Build Time: 2020-10-31 02:18:25
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.7
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai|

**Comment by marsishandsome** [comment]
I made some experiments, results are as follows:

run in MySQL-client
```
CREATE TABLE `tmp_debug` (`tp_datetime` datetime)
INSERT INTO `tmp_debug` VALUES ('0000-00-00 00:00:00')
```

run in spark-shell
```
spark.sql("select * from tmp_debug").show(false)
```

output
```
+-------------------+
|tp_datetime        |
+-------------------+
|0001-01-01 00:00:00|
+-------------------+
```

run in spark-shell
```
spark.read.jdbc(jdbcUrl, "tispark_test.tmp_debug", new Properties()).show()
```

output
```
+-------------------+
|tp_datetime        |
+-------------------+
|0001-01-01 00:00:00|
+-------------------+
```

The minimal value of type `datetime` supported by spark is `0001-01-01 00:00:00`, so the result of TiSpark and SparkJDBC is same (which is `0001-01-01 00:00:00`).

**Comment by marsishandsome** [comment]
@RUIzg would you please try SparkJDBC (spark.read.jdbc) and give me the output?

**Comment by lilinghai** [comment]
When insert into the column of  `date` type with the value of 0, the tispark value is `0001-01-03`. Is it as expected? @marsishandsome

**Comment by marsishandsome** [comment]
> When insert into the column of `date` type with the value of 0, the tispark value is `0001-01-03`. Is it as expected? @marsishandsome

The valid range of `Date` type in MySQL is `1000-01-01——9999-12-31`.
`0` is not a valid value of `Date` Type.
So to my opinion,  `0001-01-03` is a reasonable result.

**Comment by birdstorm** [comment]
This issue is closed. If it can be reproduced on the latest master branch, feel free to reopen it.
