### ISSUE TITLE
Null data integration test.

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#186]
<a href="https://github.com/Novemser"><img src="https://avatars1.githubusercontent.com/u/12718118?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Novemser](https://github.com/Novemser)**
_Wed Dec  6 09:45:52 2017_
_Originally opened as https://github.com/pingcap/tikv-client-lib-java/issues/184_

----

Need to add test data to fix problem like #183 .

**Comment by birdstorm** [comment]
<a href="https://github.com/Novemser"><img src="https://avatars1.githubusercontent.com/u/12718118?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Novemser](https://github.com/Novemser)**
_Mon Dec 11 11:51:45 2017_

----

Refer to https://github.com/pingcap/tispark/pull/126

**Comment by Novemser** [comment]
Fixed by https://github.com/pingcap/tispark/pull/126
