### ISSUE TITLE
[BUG] Insert into unique column with the statement containing same value doesn't fail

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1860]
**Describe the bug**

The issue is related to https://github.com/pingcap/tispark/issues/1512 , but it is closed for the https://github.com/pingcap/tispark/issues/1512#issuecomment-731954305. I can't reopen the issue ,so I create the new issue.
**What did you do**

1. create table in tidb
create table t1(a bigint unique key) 
2. execute in tis park
insert into st1 values(1),(2),(1)

**What do you expect**

failed
**What happens instead**

success
**Spark and TiSpark version info**

Release Version: 2.3.11-SNAPSHOT
Git Commit Hash: c7b3850ec43a520b8c751f6f4939d54fa130e8b8
Git Branch: release-2.3
UTC Build Time: 2020-12-08 04:34:00
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai
tidb: release-4.0

**Comment by shiyuhang0** [comment]
Could you please try it with tispark 2.4 or 2.5?
