### ISSUE TITLE
Refactory Expression system

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#187]
<a href="https://github.com/ilovesoup"><img src="https://avatars2.githubusercontent.com/u/3347719?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ilovesoup](https://github.com/ilovesoup)**
_Fri Dec  8 05:51:01 2017_
_Originally opened as https://github.com/pingcap/tikv-client-lib-java/issues/188_

----

1. For now we add all logic directly, we might use Visitor instead
2. Clean duplicated expressions which mostly is just placeholder.
3. Make TiConstant carry type information.

**Comment by ilovesoup** [comment]
Done.

**Comment by ilovesoup** [comment]
https://github.com/pingcap/tispark/pull/197
Actually it's a lot more than original issue's idea.
