### ISSUE TITLE
[BUG] Natural join with multiple table get different results compared with tidb

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1883]
**Describe the bug**

Natural join with multiple table get different results compared with tidb
**What did you do**

1. execute in tidb
```
create table t1 (i int);
create table t2 (i int);
create table t3 (i int);
insert into t1 values(1),(2);
insert into t2 values(2),(3);
insert into t3 values (2),(4);
```
2. execute in tispark
```
select * from t1,t2 natural right join t3
select t1.i,t2.i,t3.i from t1,t2 natural right join t3
```
**What do you expect**

`select * from t1,t2 natural right join t3`  result :
(1, 4), (1, 2), (2, 4), (2, 2)

`select t1.i,t2.i,t3.i from t1,t2 natural right join t3` result :
(1, null, 4), (1, 2, 2), (2, null, 4), (2, 2, 2)

**What happens instead**

`select * from t1,t2 natural right join t3`  result :
(4, None), (2, 2), (2, 3)

`select t1.i,t2.i,t3.i from t1,t2 natural right join t3` raise exception:
```
org.apache.hive.service.cli.HiveSQLException: org.apache.spark.sql.AnalysisException: cannot resolve '`t1.i`' given input columns: [t3.i, t2.i]; line 1 pos 7;
'Sort ['t1.i ASC NULLS FIRST, 't2.i ASC NULLS FIRST, 't3.i ASC NULLS FIRST], true
+- 'Project ['t1.i, i#392L, i#393L]
   +- Project [i#393L, i#392L]
      +- Join RightOuter, (i#391L = i#393L)
         :- Join Inner
         :  :- SubqueryAlias `t1`
         :  :  +- Relation[i#391L] TiDBRelation(TiTableReference(ticase_10006_utkpfm,t1,9223372036854775807), null)
         :  +- SubqueryAlias `t2`
         :     +- Relation[i#392L] TiDBRelation(TiTableReference(ticase_10006_utkpfm,t2,9223372036854775807), null)
         +- SubqueryAlias `t3`
            +- Relation[i#393L] TiDBRelation(TiTableReference(ticase_10006_utkpfm,t3,9223372036854775807), null)
```
**Spark and TiSpark version info**

Release Version: 2.3.11
Git Commit Hash: 527ce0337d565307d4fc660a94959521f2d70445
Git Branch: release-2.3
UTC Build Time: 2020-12-17 05:46:02
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: UTC
TIDB: v4.0.9

**Comment by shiyuhang0** [comment]
use `select * from t1,(t2 natural right join t3)` instead of `select * from t1,t2 natural right join t3` will get the right answer
`select t1.i,t2.i,t3.i from t1,t2 natural right join t3` will raise exception.

It's the difference between TiDB and spark-SQL. It's not a bug from TiSpark
