### ISSUE TITLE
The sql result is not right about sum.

### ISSUE THREAD

**Issue by erwadba** [pingcap/tispark#1891]
**Describe the bug**

**What did you do**
```
in tidb
test> create table s(id bigint);
Query OK, 0 rows affected (0.12 sec)
test> insert into s values(9223372036854775807);
Query OK, 1 row affected (0.03 sec)
test> insert into s values(9223372036854775807);
Query OK, 1 row affected (0.01 sec)
test> select sum(id) from s;
+----------------------+
| sum(id)              |
+----------------------+
| 18446744073709551614 |
+----------------------+
1 row in set (0.00 sec)
test> 

in tispark
spark-sql> use test;
spark-sql> select * from s;
9223372036854775807
9223372036854775807
Time taken: 0.398 seconds, Fetched 2 row(s)
spark-sql> select sum(id) from s;
-2
Time taken: 0.309 seconds, Fetched 1 row(s)
spark-sql> 
```

**What do you expect**

```
like tidb return 18446744073709551614 
```
**What happens instead**
```
return wrong value -2
```

**Spark and TiSpark version info**

```
spark-sql> select ti_version();
Release Version: 2.3.11
Git Commit Hash: 527ce0337d565307d4fc660a94959521f2d70445
Git Branch: release-2.3
UTC Build Time: 2020-12-17 05:46:02
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.7
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai
Time taken: 0.159 seconds, Fetched 1 row(s)
spark-sql>
```

**Comment by birdstorm** [comment]
> **Describe the bug**
> 
> **What did you do**
> 
> ```
> in tidb
> test> create table s(id bigint);
> Query OK, 0 rows affected (0.12 sec)
> test> insert into s values(9223372036854775807);
> Query OK, 1 row affected (0.03 sec)
> test> insert into s values(9223372036854775807);
> Query OK, 1 row affected (0.01 sec)
> test> select sum(id) from s;
> +----------------------+
> | sum(id)              |
> +----------------------+
> | 18446744073709551614 |
> +----------------------+
> 1 row in set (0.00 sec)
> test> 
> 
> in tispark
> spark-sql> use test;
> spark-sql> select * from s;
> 9223372036854775807
> 9223372036854775807
> Time taken: 0.398 seconds, Fetched 2 row(s)
> spark-sql> select sum(id) from s;
> -2
> Time taken: 0.309 seconds, Fetched 1 row(s)
> spark-sql> 
> ```
> 
> **What do you expect**
> 
> ```
> like tidb return 18446744073709551614 
> ```
> 
> **What happens instead**
> 
> ```
> return wrong value -2
> ```
> 
> **Spark and TiSpark version info**
> 
> ```
> spark-sql> select ti_version();
> Release Version: 2.3.11
> Git Commit Hash: 527ce0337d565307d4fc660a94959521f2d70445
> Git Branch: release-2.3
> UTC Build Time: 2020-12-17 05:46:02
> Supported Spark Version: 2.3 2.4
> Current Spark Version: 2.4.7
> Current Spark Major Version: 2.4
> TimeZone: Asia/Shanghai
> Time taken: 0.159 seconds, Fetched 1 row(s)
> spark-sql>
> ```


Hi, @erwadba 

I think you should create the table with `bigint unsigned` for Spark to promote the result of `sum` into BigDecimal.

If you run the quoted SQL with Spark+MySQL(JDBC), the result should also be -2.

**Comment by birdstorm** [comment]
I think the main reason is that Spark does not handle overflow of LongType. It is possible to add a configuration parameter for users to enable the overflow check, and promote the type of result to BigDecimal. If you are interested, I will issue a patch for TiSpark.

**Comment by erwadba** [comment]
Thank you. I will use `bigint unsigned` instead.
