### ISSUE TITLE
[BUG] invalid tiflash table replica sync progress key

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1932]
too many outputs for
```
invalid tiflash table replica sync progress key.
```

![image](https://user-images.githubusercontent.com/5574887/110072211-6496f000-7db8-11eb-98a5-018fe6636012.png)

maybe the content of `ByteSequence` should be logged.

**Comment by LittleFall** [comment]
If it's reasonable, we can change its level to `debug`.
