### ISSUE TITLE
[BUG] batch write error when using spark-sql

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1933]
tidbStmt.execute("drop table if exists t1")
    tidbStmt.execute("""
                       |CREATE TABLE t1 (a int);
                       |CREATE TABLE t2 (a int);
                       |insert into t1 values (1);
                       |""".stripMargin)
    spark.sql("insert into t2 select * from t1").show(false)

```
None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.pingcap.tispark.TiDBRelation.insert(TiDBRelation.scala:143)
```

**Comment by birdstorm** [comment]
insert select SQL is not yet supported.
