### ISSUE TITLE
Suppress index scan downgrade when only one task involved

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#196]
Current implementation always downgrade index scan to a shuffle/sort operation. It is not needed if only one task (maybe multiple region if split per task is set to more than one) involved.
Please confirm if this is the case and improve it. @Novemser

**Comment by Novemser** [comment]
Confirmed, will fix soon.

**Comment by Novemser** [comment]
Should be fixed by https://github.com/pingcap/tispark/pull/198
