### ISSUE TITLE
Integration test ignore tests logic has potential problems

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#204]
Currently we are ignoring tests by their output exceptions.

However it would contain potential problem when we are trying to locate a problem without exceptions, for instance, tests in `TestIndex`. And logic now is not friendly for bazel tests.

Maybe refactor is needed. @Novemser @zhexuany @ilovesoup

**Comment by Novemser** [comment]
Will refactor test framework to use `ScalaTest` soon.
