### ISSUE TITLE
[BUG] The official tikv-client code example has incompatibility

### ISSUE THREAD

**Issue by qumingxing** [pingcap/tispark#2081]
**Describe the bug**
The official tikv-client code example has incompatibility in release-2.3

**What did you do**
Import case code, some APIs are incompatible

**What do you expect**
Running normally

**What happens instead**
Compilation fails

**Spark and TiSpark version info**
2.3

**Comment by marsishandsome** [comment]
hi, would you please tell us which example code?

**Comment by shiyuhang0** [comment]
We are gradually migrating to official tikv-client
