### ISSUE TITLE
Can TiSpark load data from TiDB-A and then write these data to TiDB-B?

### ISSUE THREAD

**Issue by whl-2020-Hunan** [pingcap/tispark#2144]

**Comment by marsishandsome** [comment]
I recommend that reading from TiDB-A using TiSpark, writing to TiDB-B using jdbc.

**Comment by whl-2020-Hunan** [comment]
> I recommend that reading from TiDB-A using TiSpark, writing to TiDB-B using jdbc.

Thanks you, JDBC can indeed write another tidb

**Comment by whl-2020-Hunan** [comment]
![image](https://user-images.githubusercontent.com/69785008/134836918-cfcd349d-6f90-4c4f-a6a2-89718f597f0f.png)

**Comment by JazzyZhou** [comment]
can you show me one example that read from TiDB using TiSpark? thanks a lot.

**Comment by shiyuhang0** [comment]
> can you show me one example that read from TiDB using TiSpark? thanks a lot.

Spark SQL can do this, or you can use read API like
```
 spark.read
      .format("tidb")
      .option("database", database)
      .option("table", table)
      .load()
      .filter(filter condition)
```

**Comment by shiyuhang0** [comment]
close for it is not a feature request. and the question has been answered
