### ISSUE TITLE
请问TiSpark是否支持SparkML库的所有功能，与Spark兼容模式是怎样的？

### ISSUE THREAD

**Issue by lokiqoug** [pingcap/tispark#2168]
最近做项目准备采用TiDB生态，目前遇到如下疑问：
此前我们采用的是saprk+hadoop的生态，进行数据的存储和计算，最主要的是采用spqrkml算法库进行机器学习应用，
**现在准备转换为Tispark+TiDB的架构，但是不清楚Tispark与spark之间的关系是怎样的，是否支持spark的所有功能，特别是spqrkML的各种算法是否无缝支持？**
因为官网上只提到了sparkSQL，没有其他spark的组件的案例，所以提贴请教，还请帮忙解惑，谢谢！

**Comment by birdstorm** [comment]
TiSpark 只是一个 Spark 插件，提供了读取 TiKV 的功能。除了目前不能直接使用 DDL 操作 TiDB 写入的数据以外，不影响任何 Spark 其他计算功能。

**Comment by shiyuhang0** [comment]
close for it is not a feature request. and birdstorm have answer the question
