### ISSUE TITLE
add checks in the ci workflow to improve code quantity

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tispark#2187]
**Is your feature request related to a problem? Please describe.**
the project lack some checks in ci workflow, and some checks takes too much time.

**Describe the solution you'd like**
 I'd like to add some checks and speed ​​up integration test. In addtion, the fast running check will be triggered automatically and the slow running check like integration test will be triggered Manually.

**Solution detail**

 checks triggered automatically
- CodeQL
- Scala & Java fmt
- Build
- tikv-client UT

checks triggered manually
- Snoatype
- Integration test

how to speed ​​up integration test
The test PartitionTableSuite.scala takes about 50 minutes cause the overall to be too slow. i will remove it from integration test before i Optimize this test

**Comment by sunxiaoguang** [comment]
Do we have ideas to make this test faster?

**Comment by shiyuhang0** [comment]
> Do we have ideas to make this test faster?

I have known the test block in this step "WARN DAGScheduler: Broadcasting large task binary with size 78.5 MiB", but i have no idea how to make it faster

**Comment by shiyuhang0** [comment]
> > Do we have ideas to make this test faster?
> 
> I have known the test block in this step "WARN DAGScheduler: Broadcasting large task binary with size 78.5 MiB", but i have no idea how to make it faster

i have tried to speed up the test "PartitionTableSuite", but failed.So i will remove it in integration test.Meanwhile it will be put in the daily CI which will be built later
