### ISSUE TITLE
tispark-assembly-2.3.16.jar下的resources无法被引用

### ISSUE THREAD

**Issue by ajlcy** [pingcap/tispark#2190]
tispark-assembly-2.3.16.jar下的resources无法被引用，java跑时会报ClassNotFoundException错误，com.pingcap.tispark.SparkWrapper会被找不到，是什么原因

**Comment by xuanyu66** [comment]
For Tispark version > 2.0, use example is a bit different.
You can see user doc behind, it's still not merged
https://github.com/pingcap/tispark/pull/2167

**Comment by shiyuhang0** [comment]
> tispark-assembly-2.3.16.jar下的resources无法被引用，java跑时会报ClassNotFoundException错误，com.pingcap.tispark.SparkWrapper会被找不到，是什么原因

Translate to english
Import tispark-assembly-2.3.16.jar in java occurs the error ClassNotFoundException for com.pingcap.tispark.SparkWrappe. why?

**Comment by shiyuhang0** [comment]
> tispark-assembly-2.3.16.jar下的resources无法被引用，java跑时会报ClassNotFoundException错误，com.pingcap.tispark.SparkWrapper会被找不到，是什么原因

can you explain more details about the error occurs? such as the spark version, the command you excute
Besides, what do you mean about "run with java"?

**Comment by shiyuhang0** [comment]
The custom classload can't parse the SparkWrapper from jar file with `jar in jar` form. you can add `spark-wrapper-spark-version` in your dependency

**Comment by shiyuhang0** [comment]
close it
