### ISSUE TITLE
Auth don't support other datasource except TiDB

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tispark#2224]
**Is your feature request related to a problem? Please describe.**
When i use auth, i find that other datasource(except TiDB) such as hive will be affected.
for example,`show databases` can't show hive's database and `select xxx from hivetable` will fail with no authorization.
So, if i want to use auth, i must only work with TiDB.

**Describe the solution you'd like**
Auth support other datasource or not affect other datasource

**Comment by xuanyu66** [comment]
It's because auth doesn't distinguish which type the datasource is.
So if you select hive table with spark SQL, auth module would look up privilege info in TiDB, which would cause Exception.

**Comment by xuanyu66** [comment]
I think we should use another tag instead of bug.
@zhangyangyu PTAL

**Comment by shiyuhang0** [comment]
@zhangyangyu can you help to change the lable to `type/feature-request`
