### ISSUE TITLE
[BUG] Data miss when select with tispark

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tispark#2236]
**Describe the bug**

when i use sql to select with tispark, datas are not return correctly.

**What did you do**
1.  set tidb config `new_collations_enabled_on_first_bootstrap = true`
2.  create cluster index table with varchar pk through tidb
```
CREATE TABLE `test`.`t1` (
 `col_varchar` varchar(23) not null,
 `col_bit` bit(1) not null,
 `col_int` int(11) not null,
 UNIQUE KEY (`col_int`),
 PRIMARY KEY (`col_varchar`(3)) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB;
INSERT INTO `t1` VALUES ('xew1lPZtuMjEB5IKVgvplwn',b'0',-1748917164);
INSERT INTO `t1` VALUES ('1AdafDuoV86VUObqJAPBw41',b'1',647404358);
```
3. when select without double read, the datas will be fetched.or the data will miss

![image](https://user-images.githubusercontent.com/52435083/154044253-a7c2634d-cd67-40ce-bca2-4ff0eef319ad.png)

**Spark and TiSpark version info**
spark version:3.x
tispark version:master

**Solution**
I think tispark is not support collations by now. It's not clear how the new collations will affect tispark，just like i have no idea how this bug occurs. Therefore, set `new_collations_enabled_on_first_bootstrap = false` when meet related questions

**Comment by xuanyu66** [comment]
plz close this resolved issue
