### ISSUE TITLE
 one example that read from TiDB using TiSpark

### ISSUE THREAD

**Issue by superJazzy** [pingcap/tispark#2240]
## General Question 
can you show me one example that read from TiDB using TiSpark? I want to use Tispark connect to TIDB with scala，but I failed ,I hope someone can help me.  thanks a lot.

**Comment by xuanyu66** [comment]
List your steps and show the error information

**Comment by superJazzy** [comment]
Thanks for your prompt reply !
ERROR Message: Table not exist TiTableReference(dm,
(select USER_NM,PASS_WORD from user_info) as t.
Tidb Version : 3.1.0.
Tispark Version 2.4.3
my code:
 val df = sqlContext.read
        .format("tidb")
        .options(tidbOptions1)
        .option("database", "dm")
        .option("table", "(select USER_NM,PASS_WORD from user_info) as t")
        .load()
Do Tispark have this api like spark JDBC which can use sql instead of table name? 
Looking forward for your reply! Thanks a lot.

**Comment by xuanyu66** [comment]
@superJazzy Please see the user guide in https://github.com/pingcap/tispark/blob/master/docs/userguide.md#Demonstration.

use spark.sql instead of Datasource Reader.

**Comment by superJazzy** [comment]
Thanks for your reply .
I have tried spark sql but faied.

ERROR Message :
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient;

It seems that when I use "spark.sql("use dm")" the program judges I want to read tables from hive. Do I miss any confige
in config file?

**Comment by xuanyu66** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/17768378/155516284-22d90210-3439-4453-b683-a96badb1a835.png">
@superJazzy have you added this configuration

**Comment by superJazzy** [comment]
I haved added it in CDH like this
![image](https://user-images.githubusercontent.com/58155848/155519368-b726fcd2-c195-45ea-bab5-386b529808b4.png)
I used spark submit on using adding --jar tispark-assembly-2.4.3-scala_2.11.jar

**Comment by xuanyu66** [comment]
> I haved added it in CDH like this ![image](https://user-images.githubusercontent.com/58155848/155519368-b726fcd2-c195-45ea-bab5-386b529808b4.png) I used spark submit on using adding --jar tispark-assembly-2.4.3-scala_2.11.jar

[What is CDH ](https://asktug.com/t/topic/573026)
Maybe CDH spark conf is different from Apache spark. You can follow this

**Comment by superJazzy** [comment]
thank you for your reply.I have run it successfully.Thanks a lot
