### ISSUE TITLE
About GSOC2022 need help

### ISSUE THREAD

**Issue by ajian2002** [pingcap/tispark#2262]
## General Question

Hi, I am very interested in this Feature Request and I noticed that this task passes
Cloud Native Computing Foundation (CNCF) participated in Google Summer of Code: Home2022. I am an undergraduate student and would like to take this opportunity to participate in gsoc2022. How should I start? Can anyone provide me with some help and advice, I am very grateful

**Comment by xuanyu66** [comment]
Hello, welcome to contribute code.
But can you tell me where did you hear this news? we did apply for gsoc2022, but haven't gotten any response.

**Comment by ajian2002** [comment]
[cncf/mentoring](https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md)
I found tispark in this text

**Comment by xuanyu66** [comment]
https://summerofcode.withgoogle.com/ 
According to this, it will open on April.

**Comment by ajian2002** [comment]
yes , it's time to `March 7 - April 3 Potential GSoC contributors discuss application ideas with mentoring organizations`
[https://developers.google.com/open-source/gsoc/timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by xuanyu66** [comment]
OK, get your point. Hang on a moment.

**Comment by xuanyu66** [comment]
Hello, You can learn some pre-requisite knowledge.
- TiDB
	- You can get an overview of TiDB from [301 TiDB 系统管理基础](https://learn.pingcap.com/learner/course/30002). I recommend you to learn the first seven chapters.
- TiSpark
	- It's an appropriate way to get familiar with TiSpark by firstly deploying and using it. You can follow the user guide and if you find some ambiguous and inaccuracy descriptions, you can create PR to polish them.
	- If you have an interest in the insight of TiSpark. You can Lookup in [Spark catalyst](https://issues.apache.org/jira/browse/SPARK-1251), through which we get execution plans for TiKV. And also [Datasouce API V2](http://blog.madhukaraphatak.com/spark-3-datasource-v2-part-1/), which supports reading/writing from external storage. But I suggest you don't go too deep since it's not focus of this project
- TiKV-client
	- You can find the official repo in [here](https://github.com/tikv/client-java) and you can also find a module named `tikv-client` in TiSpark.

**Comment by xuanyu66** [comment]
@shiyuhang0 @zhangyangyu calling for mentors.

**Comment by zhangyangyu** [comment]
Thanks for your notice. @xuanyu66 has given a good pre-requisite knowledge list. For what jobs need to do for the task, there is a brief description in https://github.com/tikv/client-java/issues/514. 

For help and advice, you could contact me/@shiyuhang0/@xuanyu66 freely via Github/email or lark/wechat group(if you think it's more convenient).

**Comment by ajian2002** [comment]
i think this is very useful list. thank you for your help
