### ISSUE TITLE
tispark write to tidb throwing error - table with auto increment column, but data col size 2 != table column size 4 and table column size - 1 3

### ISSUE THREAD

**Issue by asksonu** [pingcap/tispark#2274]
I have created a table as below:

`CREATE TABLE aggregations_record (
  id bigint(20) unsigned  NOT NULL AUTO_INCREMENT,
  updated_at datetime(6) DEFAULT NULL,
  deleted_at datetime(6) DEFAULT NULL,
  is_deleted tinyint(1) DEFAULT 1,
  PRIMARY KEY (id)
)`

And I am trying to write through tispark to tidb as below (save_args has other details required to write). 
`row_df.write.format('tidb') \
                .options(**save_args) \
                .mode('append') \
                .save()`

I am getting below column size mismatch error: 
`table with auto increment column, but data col size 2 != table column size 4 and table column size - 1 3`

row_df structure is as below:
`
 id|is_deleted
2138103525|  0
1842406747|  0
`

Expectation is tidb should write the default values which I have set for other columns. 

Is it the tispark behaviour or is there anything else I can add for tidb to write default values if I am not passing columns explicitly ?

Note: I am running tidb using playground with version - v5.4.0 and spark version 3.1.3

Please help.

**Comment by shiyuhang0** [comment]
Thank you for your question. TiSpark doesn't support generating data for columns with default values currently. We will support it in the future version.
