### ISSUE TITLE
I'm confused when using TiSpark(master branch) on Spark3.1.3

### ISSUE THREAD

**Issue by shanhai3000** [pingcap/tispark#2275]
## General Question
The userguide.md said use `spark.sql("use tidb_catalog.tpch")` to select a tidb database, and it really works.

But then when i tried to query tables in hive, i have to execute `spark.sql("use spark_catalog")`, so here is the question:
What should i do if i want to execute a join query of table  "hive_table" and table  "tidb_table" ?

I know that maybe i could use `select xxx from spark_catalog.hive_db.hive_table join tidb_catalog.tidb_db.tidb_table on xxx`, it does work indeed, but that's really not user friendly and too much sql-jobs need to be modified.

There's no such problems in TiSpark-2.1.8( on Spark2.4)

**Comment by shiyuhang0** [comment]
Yes. The catalog will be necessary for the future TiSpark version.

**Comment by shiyuhang0** [comment]
In my view, this usage is most likely going to become the key way to interact with different datasources after Spark 3
