### ISSUE TITLE
[BUG] limit can not push down to tidb when cast expression appears

### ISSUE THREAD

**Issue by zzzzming95** [pingcap/tispark#2308]
**Describe the bug**

When the expression of `org.apache.spark.sql.catalyst.expressions.Cast` appears in parsing SQL, limit cannot be pushed down.

**What did you do**

first , in tidb create a table :
```
CREATE TABLE `test2` (
  `id` int(10) NOT NULL,
  `name` varchar(255) NOT NULL,
  `age` decimal(20,0) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

than ,use tispark run sql :
```
select * from test.test2 where age > 0.0 limit 1;
```
We can see that the limit can not push down to tidb.

**What do you expect**

Limit can push down to tidb when cast expression appears.

**What happens instead**

**Spark and TiSpark version info**

tispark : 2.4.3
spark : 2.4.0

**Comment by zzzzming95** [comment]
The problem is here. When converting `GreaterThan` to `TiExpression` during spark parsing, match fails because `org.apache.spark.sql.catalyst.expressions.Cast` cannot be converted.

https://github.com/pingcap/tispark/blob/2f5badb5bd0d90cd5a4d5f9bc5facc69d096e6c1/core/src/main/scala/org/apache/spark/sql/catalyst/expressions/BasicExpression.scala#L114

My question is whether it is necessary to add a tiexpression's `Cast` to tidb to adapt to this situation.

@shiyuhang0 @xuanyu66  cc

**Comment by zzzzming95** [comment]
Supplementary explain information

![image](https://user-images.githubusercontent.com/13965087/164978724-da9794e6-c9e4-494f-9116-f9efb4617dfd.png)

**Comment by shiyuhang0** [comment]
I will check it today
