### ISSUE TITLE
[BUG] limit cause oom

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tispark#2311]
**Describe the bug**
when I use tispark to execute "select * from table limit 10" the spark executor is OOM killed 

**What did you do**
1. Run spark.sql("select * from qk_chi.perio_artical limit 10").show  on k8s ，the executor is OOMKilled.
2. Run  spark.sql("select * from qk_chi.perio_artical").show  on k8s ,it is OK.
3. Run  spark.sql("select * from qk_chi.perio_artical limit 10").show  on yarn ,the executor is OOMKilled.
4. Run  spark.sql("select * from qk_chi.perio_artical").show  on yarn ,it is OK.

![image](https://user-images.githubusercontent.com/22764286/165230459-cb9bafcb-d674-43e1-823c-bff998540cde.png)

![image](https://user-images.githubusercontent.com/22764286/165230475-254aaa00-c5d4-47e9-b490-0b68e7b95792.png)

**Spark and TiSpark version info**
spark version: v3.0.1
tispark version: v2.5.0
tidb version: v5.1.1

**Comment by shiyuhang0** [comment]
can you provide 
1. version info：spark version/tidb version/tispark version
2.  run spark.sql("select * from qk_chi.perio_artical limit 10").explain

**Comment by wfxxh** [comment]
`== Parsed Logical Plan ==
'GlobalLimit 10
+- 'LocalLimit 10
   +- 'Project [*]
      +- 'UnresolvedRelation [qk_chi, perio_artical], [], false

== Analyzed Logical Plan ==
random_id: string, article_id: string, perio_id: string, issue_id: string, perio_title: string, trans_title: string, doi: string, article_seq: bigint, article_title: string, en_title: string, authors_name: string, trans_authors: string, authors_unit: string, column_name: string, trans_column: string, publish_year: string, volume: string, issue_num: string, abstract: string, orig_abstract: string, trans_abstract: string, text_segment: string, language: string, trans_language: string, ... 61 more fields
GlobalLimit 10
+- LocalLimit 10
   +- Project [random_id#6, article_id#7, perio_id#8, issue_id#9, perio_title#10, trans_title#11, doi#12, article_seq#13L, article_title#14, en_title#15, authors_name#16, trans_authors#17, authors_unit#18, column_name#19, trans_column#20, publish_year#21, volume#22, issue_num#23, abstract#24, orig_abstract#25, trans_abstract#26, text_segment#27, language#28, trans_language#29, ... 61 more fields]
      +- SubqueryAlias perio_artical
         +- Relation[random_id#6,article_id#7,perio_id#8,issue_id#9,perio_title#10,trans_title#11,doi#12,article_seq#13L,article_title#14,en_title#15,authors_name#16,trans_authors#17,authors_unit#18,column_name#19,trans_column#20,publish_year#21,volume#22,issue_num#23,abstract#24,orig_abstract#25,trans_abstract#26,text_segment#27,language#28,trans_language#29,... 61 more fields] TiDBRelation(TiTableReference(qk_chi,perio_artical,8525319628473757854), null)

== Optimized Logical Plan ==
GlobalLimit 10
+- LocalLimit 10
   +- Relation[random_id#6,article_id#7,perio_id#8,issue_id#9,perio_title#10,trans_title#11,doi#12,article_seq#13L,article_title#14,en_title#15,authors_name#16,trans_authors#17,authors_unit#18,column_name#19,trans_column#20,publish_year#21,volume#22,issue_num#23,abstract#24,orig_abstract#25,trans_abstract#26,text_segment#27,language#28,trans_language#29,... 61 more fields] TiDBRelation(TiTableReference(qk_chi,perio_artical,8525319628473757854), null)

== Physical Plan ==
CollectLimit 10
+- *(1) ColumnarToRow
   +- TiKV CoprocessorRDD{[table: perio_artical] TableScan, Columns: random_id@VARCHAR(255), article_id@VARCHAR(255), perio_id@VARCHAR(255), issue_id@VARCHAR(255), perio_title@VARCHAR(255), trans_title@VARCHAR(65535), doi@VARCHAR(255), article_seq@LONG, article_title@VARCHAR(65535), en_title@VARCHAR(4294967295), authors_name@VARCHAR(4294967295), trans_authors@VARCHAR(4294967295), authors_unit@VARCHAR(4294967295), column_name@VARCHAR(255), trans_column@VARCHAR(65535), publish_year@VARCHAR(255), volume@VARCHAR(255), issue_num@VARCHAR(255), abstract@VARCHAR(4294967295), orig_abstract@VARCHAR(4294967295), trans_abstract@VARCHAR(4294967295), text_segment@VARCHAR(4294967295), language@VARCHAR(255), trans_language@VARCHAR(255), keywords@VARCHAR(255), orig_keys@VARCHAR(65535), trans_keys@VARCHAR(4294967295), auto_keys@VARCHAR(4294967295), head_words@VARCHAR(4294967295), head_table@VARCHAR(4294967295), class_code@VARCHAR(255), orig_classcode@VARCHAR(65535), orig_class@VARCHAR(4294967295), auto_classcode@VARCHAR(65535), page_range@VARCHAR(255), page_cnt@LONG, doc_num@VARCHAR(255), literature_code@VARCHAR(255), received_date@DATETIME@Asia/Shanghai, revised_date@DATETIME@Asia/Shanghai, orig_pub_date@DATETIME@Asia/Shanghai, pro_pub_date@DATETIME@Asia/Shanghai, abst_webdate@DATETIME@Asia/Shanghai, full_pubdate@DATETIME@Asia/Shanghai, abstract_url@VARCHAR(255), full_url@VARCHAR(255), is_fulltext@VARCHAR(255), is_oa@VARCHAR(255), service_model@VARCHAR(255), cn@VARCHAR(255), issn@VARCHAR(255), hxkbj_istic@VARCHAR(255), hxkbj_pku@VARCHAR(255), hxkbj_nd@VARCHAR(255), hxkbj_ei@VARCHAR(255), hxkbj_sci@VARCHAR(255), refdoc_cnt@LONG, linkdoc_cnt@LONG, cited_cnt@LONG, fund_info@VARCHAR(4294967295), core_perio@VARCHAR(255), is_nstl@LONG, first_publish@LONG, source_db@VARCHAR(255), first_authors@VARCHAR(65535), batch_id@LONG, classname_1@VARCHAR(4294967295), classname_2@VARCHAR(4294967295), classname_3@VARCHAR(4294967295), down_count@LONG, view_count@LONG, org_name@VARCHAR(4294967295), new_org@VARCHAR(4294967295), auth_area@VARCHAR(65535), auth_city@VARCHAR(65535), auth_county@VARCHAR(65535), education_code@VARCHAR(65535), primary_partition@LONG, last_modify_time@TIMESTAMP, as_delete@LONG, projectid@VARCHAR(4294967295), fundgroupnamezh@VARCHAR(65535), projectgrantno@VARCHAR(65535), isthirdservice@LONG, spark_update_time@DATETIME@Asia/Shanghai, KeyRange: [([t\200\000\000\000\000\000\000\215_r\000\000\000\000\000\000\000\000], [t\200\000\000\000\000\000\000\215_s\000\000\000\000\000\000\000\000])], Limit: [10], startTs: 432770655152766977} EstimatedCount:99246789

============================== with limit 10 ==============================

== Parsed Logical Plan ==
'Project [*]
+- 'UnresolvedRelation [qk_chi, perio_artical], [], false

== Analyzed Logical Plan ==
random_id: string, article_id: string, perio_id: string, issue_id: string, perio_title: string, trans_title: string, doi: string, article_seq: bigint, article_title: string, en_title: string, authors_name: string, trans_authors: string, authors_unit: string, column_name: string, trans_column: string, publish_year: string, volume: string, issue_num: string, abstract: string, orig_abstract: string, trans_abstract: string, text_segment: string, language: string, trans_language: string, ... 61 more fields
Project [random_id#176, article_id#177, perio_id#178, issue_id#179, perio_title#180, trans_title#181, doi#182, article_seq#183L, article_title#184, en_title#185, authors_name#186, trans_authors#187, authors_unit#188, column_name#189, trans_column#190, publish_year#191, volume#192, issue_num#193, abstract#194, orig_abstract#195, trans_abstract#196, text_segment#197, language#198, trans_language#199, ... 61 more fields]
+- SubqueryAlias perio_artical
   +- Relation[random_id#176,article_id#177,perio_id#178,issue_id#179,perio_title#180,trans_title#181,doi#182,article_seq#183L,article_title#184,en_title#185,authors_name#186,trans_authors#187,authors_unit#188,column_name#189,trans_column#190,publish_year#191,volume#192,issue_num#193,abstract#194,orig_abstract#195,trans_abstract#196,text_segment#197,language#198,trans_language#199,... 61 more fields] TiDBRelation(TiTableReference(qk_chi,perio_artical,8525319628473757854), null)

== Optimized Logical Plan ==
Relation[random_id#176,article_id#177,perio_id#178,issue_id#179,perio_title#180,trans_title#181,doi#182,article_seq#183L,article_title#184,en_title#185,authors_name#186,trans_authors#187,authors_unit#188,column_name#189,trans_column#190,publish_year#191,volume#192,issue_num#193,abstract#194,orig_abstract#195,trans_abstract#196,text_segment#197,language#198,trans_language#199,... 61 more fields] TiDBRelation(TiTableReference(qk_chi,perio_artical,8525319628473757854), null)

== Physical Plan ==
*(1) ColumnarToRow
+- TiKV CoprocessorRDD{[table: perio_artical] TableScan, Columns: random_id@VARCHAR(255), article_id@VARCHAR(255), perio_id@VARCHAR(255), issue_id@VARCHAR(255), perio_title@VARCHAR(255), trans_title@VARCHAR(65535), doi@VARCHAR(255), article_seq@LONG, article_title@VARCHAR(65535), en_title@VARCHAR(4294967295), authors_name@VARCHAR(4294967295), trans_authors@VARCHAR(4294967295), authors_unit@VARCHAR(4294967295), column_name@VARCHAR(255), trans_column@VARCHAR(65535), publish_year@VARCHAR(255), volume@VARCHAR(255), issue_num@VARCHAR(255), abstract@VARCHAR(4294967295), orig_abstract@VARCHAR(4294967295), trans_abstract@VARCHAR(4294967295), text_segment@VARCHAR(4294967295), language@VARCHAR(255), trans_language@VARCHAR(255), keywords@VARCHAR(255), orig_keys@VARCHAR(65535), trans_keys@VARCHAR(4294967295), auto_keys@VARCHAR(4294967295), head_words@VARCHAR(4294967295), head_table@VARCHAR(4294967295), class_code@VARCHAR(255), orig_classcode@VARCHAR(65535), orig_class@VARCHAR(4294967295), auto_classcode@VARCHAR(65535), page_range@VARCHAR(255), page_cnt@LONG, doc_num@VARCHAR(255), literature_code@VARCHAR(255), received_date@DATETIME@Asia/Shanghai, revised_date@DATETIME@Asia/Shanghai, orig_pub_date@DATETIME@Asia/Shanghai, pro_pub_date@DATETIME@Asia/Shanghai, abst_webdate@DATETIME@Asia/Shanghai, full_pubdate@DATETIME@Asia/Shanghai, abstract_url@VARCHAR(255), full_url@VARCHAR(255), is_fulltext@VARCHAR(255), is_oa@VARCHAR(255), service_model@VARCHAR(255), cn@VARCHAR(255), issn@VARCHAR(255), hxkbj_istic@VARCHAR(255), hxkbj_pku@VARCHAR(255), hxkbj_nd@VARCHAR(255), hxkbj_ei@VARCHAR(255), hxkbj_sci@VARCHAR(255), refdoc_cnt@LONG, linkdoc_cnt@LONG, cited_cnt@LONG, fund_info@VARCHAR(4294967295), core_perio@VARCHAR(255), is_nstl@LONG, first_publish@LONG, source_db@VARCHAR(255), first_authors@VARCHAR(65535), batch_id@LONG, classname_1@VARCHAR(4294967295), classname_2@VARCHAR(4294967295), classname_3@VARCHAR(4294967295), down_count@LONG, view_count@LONG, org_name@VARCHAR(4294967295), new_org@VARCHAR(4294967295), auth_area@VARCHAR(65535), auth_city@VARCHAR(65535), auth_county@VARCHAR(65535), education_code@VARCHAR(65535), primary_partition@LONG, last_modify_time@TIMESTAMP, as_delete@LONG, projectid@VARCHAR(4294967295), fundgroupnamezh@VARCHAR(65535), projectgrantno@VARCHAR(65535), isthirdservice@LONG, spark_update_time@DATETIME@Asia/Shanghai, KeyRange: [([t\200\000\000\000\000\000\000\215_r\000\000\000\000\000\000\000\000], [t\200\000\000\000\000\000\000\215_s\000\000\000\000\000\000\000\000])], startTs: 432770655454232577} EstimatedCount:99246789

`

**Comment by shiyuhang0** [comment]
I see two plans. can you tell me the corresponding SQL ?

**Comment by shiyuhang0** [comment]
1. can you show executor's log when Run spark.sql("select * from qk_chi.perio_artical limit 10").show

**Comment by wfxxh** [comment]
**1. executor log when run sql with limit:**
   22/04/27 16:14:16 INFO KVErrorHandler: Accumulating cache invalidation info to driver:regionId=1514687,storeId=274433475,type=REQ_FAILED
22/04/27 16:14:16 INFO KVErrorHandler: Accumulating cache invalidation info to driver:regionId=275005825,storeId=274433475,type=REQ_FAILED
22/04/27 16:14:16 INFO KVErrorHandler: Accumulating cache invalidation info to driver:regionId=274891600,storeId=274433475,type=REQ_FAILED
22/04/27 16:14:16 INFO KVErrorHandler: Accumulating cache invalidation info to driver:regionId=274496287,storeId=274433475,type=REQ_FAILED
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:16 WARN RegionStoreClient: Re-splitting region task due to region error: TiKV down or Network partition
22/04/27 16:14:17 ERROR CoarseGrainedExecutorBackend: RECEIVED SIGNAL TERM

2. executor memory without limit is 418.38MB
3. executor memory is 4G and yarn.scheduler.maximum-allocation-mb is 64G

**Comment by shiyuhang0** [comment]
Please set `spark.executor.memory` to 3g and retry the OOM case.
Maybe the limit needs off-heap memory and the total request by (spark.executor.memory + off-heap memory) > 4G

**Comment by wfxxh** [comment]
It can not be the memory insufficient. The statement with limit can work!

**Comment by shiyuhang0** [comment]
what the error is when you set the spark.executor.memory to 8g

**Comment by wfxxh** [comment]
It OOM too！

**Comment by shiyuhang0** [comment]
can you show the error

**Comment by wfxxh** [comment]
![image](https://user-images.githubusercontent.com/22764286/167402549-0d4592a8-cee1-45f0-946f-04acf2050c1b.png)

**Comment by shiyuhang0** [comment]
do you leave some memory for worker? for example when your worker's memory is 8G, spark.executor.memory should not set to 8g

**Comment by wfxxh** [comment]
Of course,I am not a tyro! Please do not ask this low question !

**Comment by shiyuhang0** [comment]
But in your

**Comment by wfxxh** [comment]
This is not the latest config,the picture is just an history.whatever the size of executor memory i set , the statement with limit cause OOM  and the statement without limit do not cause OOM

**Comment by shiyuhang0** [comment]
Please provide the OOM info like the picture and the corresponding configuration（yarn and spark）
or you can increase the memory overhead for testing if the limit statement needs more off-heap memory

**Comment by shiyuhang0** [comment]
can you try `spark.sql("select * from qk_chi.perio_artical").limit(10).show` to test if spark limit will cause OOM

**Comment by wfxxh** [comment]
![image](https://user-images.githubusercontent.com/22764286/167571146-124beabc-6015-45b4-acf3-4d3ade7fa749.png)
this is my submit config , `spark.sql("select * from qk_chi.perio_artical").limit(10).show` cause OOM too

**Comment by shiyuhang0** [comment]
I believe this pr https://github.com/pingcap/tispark/pull/2329 will solve your problems, wait for the merge

**Comment by wfxxh** [comment]
Thanks
