### ISSUE TITLE
Table not found when TiDB has more than 10,000 tables in a DB

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tispark#2368]
## Enhancement
When TiDB has more than 10,000 tables in one Database, TiSpark may throw exceptions like `Table not found`.

This problem may be because of the large schema, if so, we need to clarify how large the schema will lead to the problem. 

### Verison
TiDB 5.4
Spark 3.1.3
TiSpark 2.5

**Comment by TrafalgarRicardoLu** [comment]
I have create 10000 table and try select statement, but there is no exception. 

Could you describe you problem in detail, like how many columns each table has and how do you use TiSpark?

**Comment by shiyuhang0** [comment]
It may have something with concurrency.
- DDL will be put in a queue to execute one by one in TiDB, so it may not finish all the DDL when we start TiSpark.
- TiSpark will load table info into a table cache, which will be updated once the schemaVersion has been changed.

Here come the problems: the first thread loads the cache when the DDL is not finished, and the second thread loads the cache when the DDL is finished. but the first one is slower than the second one, the cache will be the first one finally. schemaVersion will be the second one
