### ISSUE TITLE
Does TiDB Connector supports  Spark 3.0+

### ISSUE THREAD

**Issue by chenjunbiao001** [pingcap/tispark#2392]
## General Question

**Comment by zhangyangyu** [comment]
Yes, it supports. Check https://github.com/pingcap/tispark/wiki/Getting-TiSpark for support matrix.

**Comment by chenjunbiao001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已收到，感谢您的来信！
