### ISSUE TITLE
[BUG] TiSparkTeleInfo.requestPD method url stitching error

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tispark#2474]
**Describe the bug**

Get pd address from config and stitching  the pd request url is wrong

**What did you do**

1. set all pd address split by comma 
2. run sql select

**Spark and TiSpark version info**

v 3.0.1

the code is 
![image](https://user-images.githubusercontent.com/22764286/181906931-f39ff40e-23b7-4105-8029-77640847cacb.png)

the url is wrong

**Comment by xuanyu66** [comment]
https://github.com/pingcap/tispark/pull/2473
@wfxxh The fix PR has been created
