### ISSUE TITLE
[BUG] Unexpected warning:ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.7.1

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [pingcap/tispark#2490]
**Describe the bug**
When running under spark 3.1.x and spark 3.2.x, you will get a warning:ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.7.122/07/27 22:53:34 WARN HttpClientUtil: Failed to send HTTP get request.

**What did you do**
Runtime Environment：
TiDB v5.4.2，Spark v3.1.x，TISpark tispark-assembly-3.1_2.12-3.0.1.jar
or
TiDB v5.4.2，Spark v3.2.x，TISpark tispark-assembly-3.2_2.12-3.0.1.jar
1.Set the correct parameters in the file:${SPARK_HOME}/conf/spark-defaults.conf
2.run bin/spark-sql
3.show databases;

**What do you expect**
Show correct results without warning:ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.8 used for parser compilation does not match the current runtime version 4.7.122/07/27 22:53:34 WARN HttpClientUtil: Failed to send HTTP get request.

**What happens instead**
The warning is displayed, which makes new users disturbed and unable to troubleshoot the correct errors. This error is often encountered in the community. Most users stay in this step and eventually lose.

**Screenshots**
![image](https://user-images.githubusercontent.com/4351491/182831387-22a7e762-5372-41e5-8555-e0fe67080ad0.png)

**Spark and TiSpark version info**
TiDB v5.4.2，Spark v3.1.x，TISpark tispark-assembly-3.1_2.12-3.0.1.jar
or
TiDB v5.4.2，Spark v3.2.x，TISpark tispark-assembly-3.2_2.12-3.0.1.jar

**Additional context**
This error is often encountered in the community. Most users stay in this step and eventually lose. Since it is an official product, it should have a certain seriousness and make it easy for users to understand and troubleshoot errors.

**Comment by WholeWorld-Timothy** [comment]
Reference:https://asktug.com/t/topic/842805

**Comment by WholeWorld-Timothy** [comment]
Can using the exclusions tab solve the problem?

**Comment by shiyuhang0** [comment]
we will resolve it recently
