### ISSUE TITLE
tispark 3.x version read speed is slower than tispark 2.5

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tispark#2573]
**tidb version is 5.4.2
spark version 3.0 to 3.2
tispark version 3.0 to 3.1**
I used tispark2.5 before, but when i upgrade tispark version to 3.x ,I find it is slow when read tikv than tispark 2.5 version。

table info :

![image](https://user-images.githubusercontent.com/22764286/196907298-8e3a77ee-8167-4e5f-b0a3-1f6de38a580b.png)

spark conf ：

![image](https://user-images.githubusercontent.com/22764286/196907374-31cb608b-7ccf-47e0-be23-6c488cf3f60e.png)

tispark 2.5:

![image](https://user-images.githubusercontent.com/22764286/196907543-ce264cc8-83ee-403d-a29f-ec9110f487d1.png)

tispark 3.x:

![image](https://user-images.githubusercontent.com/22764286/196907652-dbfb5527-adbd-417c-b49c-ee7942e1f5a6.png)

**Comment by wfxxh** [comment]
I have found the reasion,it is because the v2.5 version return TiDAGRequest object is not the same as v3.x. The 2.5 version TiDAGRequest object isDoubleRead field is false .
User can set spark.tispark.plan.allow_index_read=false to avoid

**Comment by xuanyu66** [comment]
So sounds like it's a bug?
