### ISSUE TITLE
[BUG] CI on TiDB master failed

### ISSUE THREAD

**Issue by xuanyu66** [pingcap/tispark#2585]
It still works at
https://ci2.pingcap.net/blue/organizations/jenkins/tispark_ghpr_integration_test/detail/tispark_ghpr_integration_test/1212/pipeline/
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/17768378/199924557-f7d7f9ac-5644-4381-9b4b-1e877faa6c6f.png">

First break took place at
https://ci2.pingcap.net/blue/organizations/jenkins/tispark_ghpr_integration_test/detail/tispark_ghpr_integration_test/1213/pipeline
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/17768378/199924795-309af68a-63db-46ac-a2fa-1b14c703e8d5.png">

**Comment by shiyuhang0** [comment]
closed by https://github.com/pingcap/tispark/pull/2598
