### ISSUE TITLE
OOM when using statistics

### ISSUE THREAD

**Issue by xuanyu66** [pingcap/tispark#2587]
## General Question
Is there any cache in tispark ? When i use this PR to run my process,the tikv read task number is correct,same as table region number.If I only process one table it is success.But if I loop process several tables it cause executor OOM。

**loop process several tables:**

![image](https://user-images.githubusercontent.com/22764286/200453335-8cb6c035-193f-467c-9c39-5f129a9a4280.png)

![image](https://user-images.githubusercontent.com/22764286/200453474-44379476-b891-4b67-90ac-eadb051acc3d.png)

**process the oom table when the loop is processed separately**

![image](https://user-images.githubusercontent.com/22764286/200453928-6fbb3d6a-12c9-4dbd-8467-2dc651612cbf.png)

**my process**

![image](https://user-images.githubusercontent.com/22764286/200454243-55608dc3-2725-41d3-b118-86f44c8d4d4d.png)

**Comment by xuanyu66** [comment]
@wfxxh We discuss this issue here

**Comment by wfxxh** [comment]
@xuanyu66 I am so sorry , I run application on standalone cluster, it does not OOM,I think run on k8s OOM just because my k8s cluster memory insufficient ,so it is not a bug. I am so sorry.

**Comment by xuanyu66** [comment]
@wfxxh No worries, it's common. 
I will close this issue.
