### ISSUE TITLE
单表插入太慢

### ISSUE THREAD

**Issue by dgLyonWang** [pingcap/tispark#2633]
bsSaleInvoiceDF.repartition(32).write()
                .format("tidb")
                .option("database", "misumi_service_test")
                .option("table", "bs_sale_invoice_copy1")
                .options(tidbOptionsMap)
                .mode(SaveMode.Append)
                .save();
这个代码再进行单表插入的时候，十分的慢。commit 都是单条，有没别的属性可以设置，类似jdbc的.option(JDBCOptions.JDBC_BATCH_INSERT_SIZE, 2000)一样

**Comment by shiyuhang0** [comment]
which version do you use

**Comment by dgLyonWang** [comment]
> 
tispark  3.2.0

**Comment by shiyuhang0** [comment]
TiSpark 3.2.0 uses upstream client-java. This bug has been fixed in the upstream client-java https://github.com/tikv/client-java/pull/724.
You can wait for the release of client-java and TiSpark v3.2.1. or you can choose TiSpark < 3.2 first

**Comment by dgLyonWang** [comment]
thanks
