### ISSUE TITLE
Question about tikv-client, please help me!

### ISSUE THREAD

**Issue by mxd-321** [pingcap/tispark#2636]
How does TiSpark obtain TiKV data?

Is it by obtaining the raft log of TiKV?

Is the corresponding cdc event obtained through tikv-client?

@Dieken  please help me！thank you！

**Comment by zhangyangyu** [comment]
TiSpark obtains TiKV data by tikv/client-java in the latest release. For CDC event, currently, there is no official supported client/driver to consume it.

**Comment by mxd-321** [comment]
> TiSpark obtains TiKV data by tikv/client-java in the latest release. For CDC event, currently, there is no official supported client/driver to consume it.

@zhangyangyu thank you！I still have a question, how does tikv/client-java obtain the incremental data of TiKV? Is it driven by jdbc?

**Comment by zhangyangyu** [comment]
no, tikv/client-java cannot obtain the incremental data(the CDC feature). It's not a JDBC driver, it talks to TiKV via GRPC.

**Comment by mxd-321** [comment]
> no, tikv/client-java cannot obtain the incremental data(the CDC feature). It's not a JDBC driver, it talks to TiKV via GRPC.

@zhangyangyu ok, thank you for your answer ! What tikv/client-java obtains is the raft log generated by the region leader, can I understand it this way?

**Comment by shiyuhang0** [comment]
client-java just read the batch data via RPC provided by TiKV which reads with RocksDB SST file. So, TiSpark does not support streaming now.

- If you want to learn more about how TiKV reads data, you can open an issue here https://github.com/tikv/tikv.
- If you want to learn more about ingesting incremental data of TiKV, you can open an issue here https://github.com/pingcap/tiflow

**Comment by mxd-321** [comment]
> client-java just read the batch data via RPC provided by TiKV which reads with RocksDB SST file. So, TiSpark does not support streaming now.
> 
> * If you want to learn more about how TiKV reads data, you can open an issue here https://github.com/tikv/tikv.
> * If you want to learn more about ingesting incremental data of TiKV, you can open an issue here https://github.com/pingcap/tiflow

@shiyuhang0  ok， thank you！I will open an issue here [https://github.com/pingcap/tiflow](url)
