### ISSUE TITLE
support upsert write

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#2684]
通过tispark 写入，如果主键相同，是否根据主键更新写入，避免出现：Caused by: org.tikv.common.exception.TiBatchWriteException: data to be inserted has conflicts with TiKV data。
可以添加一个参数控制是否upsert 写入

**Comment by xuanyu66** [comment]
https://github.com/pingcap/tispark/blob/master/docs/features/datasource_api_userguide.md#replace-and-insert-syntaxes
