### ISSUE TITLE
[BUG] 怎么设置一次只提交多条数据？

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#2691]
怎么设置一次只提交提交记录？看日志一次commit 一条记录，比较慢
![image](https://user-images.githubusercontent.com/1145830/234247758-4595b20f-c4a9-4411-a6f3-54a59bcdc216.png)

![image](https://user-images.githubusercontent.com/1145830/234247540-b0459aca-f2eb-4718-a426-5a95ae4a1bdf.png)

另外遇到一个问题，就是数据写入完成，连接spark 程序不能退出来：
![image](https://user-images.githubusercontent.com/1145830/234248089-4bcbb192-9781-4fa8-acba-77c86a124d2a.png)

**Comment by xuanyu66** [comment]
https://github.com/pingcap/tispark/issues/2633
