### ISSUE TITLE
Index key range is incorrect

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#271]
checking its cause which made CI fails on master branch

**Comment by birdstorm** [comment]
found corresponding pull request in tidb @Novemser 
maybe we should check our histogram impplementation as well
github.com/pingcap/tidb/pull/6034

**Comment by Novemser** [comment]
We had fixed this issue before. https://github.com/pingcap/tispark/pull/240

**Comment by birdstorm** [comment]
we haven't implemented `splitRange` function yet, so it is safe to close this issue. @Novemser

**Comment by Novemser** [comment]
What is a `splitRange` function, could you please explain this in more details? @birdstorm

**Comment by birdstorm** [comment]
you may simply refer to the pr link above. `splitRange` is for cutting key ranges according to histogram.
