### ISSUE TITLE
select查询语句中where条件为主键字段时，无法查出数据

### ISSUE THREAD

**Issue by Leon-cn** [pingcap/tispark#2738]
example:
table A, index: name, txn_date
select * from A where name = 'sss'
A表中存在name为sss的数据，但通过tispark使用spark sql时上述sql无法查出数据。

**Comment by shiyuhang0** [comment]
which version of tispark and tidb do you use

**Comment by lizhenhuan** [comment]
spark3.2.3+tispark-assembly-3.2_2.12-3.1.2+scala2.12.15

**Comment by shiyuhang0** [comment]
can you update TiSpark version to 3.1.3 to have a try?

**Comment by Leon-cn** [comment]
> can you update TiSpark version to 3.1.3 to have a try? I think this bug has been fixed in #2665 and release in v3.1.3

v3.1.3 is right

**Comment by shiyuhang0** [comment]
v3.1.4 has been released. I think this issue can be closed. reopen it if you have any other questions
