### ISSUE TITLE
tispark configuration be set at runtime not work

### ISSUE THREAD

**Issue by iodone** [pingcap/tispark#281]
work well:
```
val ss = SparkSession.builder
      .master("local")
      .appName("TiSpark Application")
      .config("spark.tispark.pd.addresses", "192.168.200.151:2379, 192.168.200.169:2379, 192.168.200.170:2379")
      .appName("TiSpark Application")
      .getOrCreate()

  val tc = new TiContext(ss)

```

not work: 
```
al ss = SparkSession.builder
      .master("local")
      .appName("TiSpark Application")
      .getOrCreate()

  ss.conf.set("spark.tispark.pd.addresses", "192.168.200.151:2379, 192.168.200.169:2379, 192.168.200.170:2379")
  val tc = new TiContext(ss)

throw exception:
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.SparkConf.get(SparkConf.scala:243)
	at com.pingcap.tispark.TiUtils$.sparkConfToTiConf(TiUtils.scala:163)
	at org.apache.spark.sql.TiContext.<init>(TiContext.scala:29)
	at com.iodone.example.TiSparkAPP$.delayedEndpoint$com$iodone$example$TiSparkAPP$1(TiSparkAPP.scala:21)
```

**Comment by iodone** [comment]
Need to configure tidpark related parameters at runtime, can you give some suggestions?

**Comment by Novemser** [comment]
Sorry, we currently do not support pd addresses dynamic configuration, since there's a lot of work to be done across the cluster to switch to brand new pds. @iodone

**Comment by ilovesoup** [comment]
PS, what's the use case for this? Are you using multiple tidb clusters and using spark to connect to all of them?

**Comment by iodone** [comment]
@ilovesoup 目前我们对spark做了一些封装，作为一个常驻服务，支持API的方式接入其他数据源，提供可插拔的接入方式。如果要接入tidb也想通过即用即配的方式，只是想在对外接口层面保持一致，这种动态配置也不是强需求，已经改为sparkSession init的时候传入pd server address。
另外还有两个疑问帮忙解答一下：
1. 初始化的时候通过 ti.tidbMapDatabase mapping 数据库的所有表到sparksql, 如果后续新增tidb的表是否不可见？
2. 是否提供按需加载tidb table 的方式，例如ti.tidbMapTable(tableName)?
因为当前spark是作为我们的常驻服务启动的，不能频繁重启，才会有以上两个疑问，请帮忙解答一下，十分感谢哇

**Comment by ilovesoup** [comment]
@iodone 
通过shell入口进去的是需要手动同步库的，但是有一个接口tidbTable(dbName, tableName)可用于单表同步。
tispark-sql和thriftserver入口则是直接桥接metastore，所以不需要做同步。
