### ISSUE TITLE
Update TiDB to 2.0RC1 then TiSpark can not get data

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tispark#282]
Update TiDB cluster from 1.1 to 2.0RC1.
TiSpark can only get schema but can't get data.
TiSpark can get data when using TiDB 1.1.

These step:
```
./spark-shell --jars /opt/spark/dist/tispark-0.1.0-SNAPSHOT-jar-with-dependencies.jar

import org.apache.spark.sql.TiContext
val ti = new TiContext (spark)
ti.tidbMapDatabase ("test")
spark.sql("select * from sequencek").show

```
Nothing in TiSpark.
spark.sql("select * from sequencek").show
+---+
| id|
+---+
+---+

1000 records in TiDB.
MySQL [test]> select * from sequencek;
+------+
| id   |
+------+
|    1 |
...
| 1000 |
+------+
1000 rows in set (59.84 sec)

Release Version:  v2.0.0-rc.1-21-g46f938c
Git Commit Hash:  46f938c632103ba7143775e884be33a1875cfa45
Git Commit Branch:  master
UTC Build Time:  2018-03-12 04:25:56
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  1.1.0-dev.2

6 servers to deploy TiDB cluster.
.1 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.2 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.3 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.4 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV
.5 E5620 CPU, 32G RAM, SAS HDD, TiDB
.6 E5620 CPU, 32G RAM, SAS HDD, TiDB
each running CentOS 7.

**Comment by Novemser** [comment]
Could you please specify how
`spark.sql("select * from sequencek").explain`
looks, and your `spark-defaults.conf` looks?

Thank you. @DavisLinDB

**Comment by DavisLinDB** [comment]
@Novemser 

explain is:
== Physical Plan ==
TiDB CoprocessorRDD{
 Table: sequencek
 Ranges: Start:[-9223372036854775808], End: [9223372036854775807]
 Columns: [id]
}

spark-defaults.conf is:
spark.tispark.pd.addresses 192.168.29.151:2379,192.168.29.152:2379,192.168.29.153:2379

**Comment by ilovesoup** [comment]
@DavisLinDB We can't reproduce this behavior right now. If possible, would you please contact me via email and we in turn might chat via IM like wechat?
maxiaoyu@pingcap.com

**Comment by DavisLinDB** [comment]
new jar fix it.
