### ISSUE TITLE
Linear Algebra Data Types

### ISSUE THREAD

**Issue by mickdelaney** [pingcap/tispark#300]
Does TiKV support Vector data for Linear algebra. 
I'm evaluating whether we could use TiKV/TiSpark/TiDB for serving queries from our machine learning models. We do alot of vector based similarity searching etc, using things like cosine similarity over vectors, matrices etc.
We use Apache MadLib with Postgres, and PrestoDB for serving these types of queries also. 
Regards

**Comment by ilovesoup** [comment]
@mickdelaney I'm not quite familiar with ML stuff. 
What concrete type did you use for PrestoDB or PG cases? Is it an Array?
If so, I think the best of hope for now is using blob type with UDF to unpack it to an array. After reading, the rest of the part works like native.

**Comment by mickdelaney** [comment]
We use an array of Array of double & we initially used the consine_similarity function here: https://prestodb.io/docs/current/functions/math.html

but ended up with our own function: 
reduce(
   zip_with(
	   ARRAY{target_vector_array_str},
	   vector,
	   (x, y) -> x * y
   ),
   0.0,
   (s, x) -> s + x, s -> s
)

**Comment by mickdelaney** [comment]
target_vector_array_str something like:  

ARRAY[0.498103843558768,0.08470424978456259,0.2631435350302188,0.3934188650368525,0.4179578779765668,0.22149724486477518,0.36467130787458213,0.29915134858963544,0.3102449968870319,0.10450888521174573,0.1144633380455341,0.7249993533682562,0.9376279741266519,0.8435073548308901,0.08656169804061176,0.7983901865864684,0.34760616480970263,0.711228375236424,0.6067116548656752,0.1671451046068596,0.5238343261772648,0.768364552959512,0.22740564425593668,0.9923396498847372,0.4820261494378488,0.7814718321813844,0.4859395897077362,0.5109053056286057,0.8920726571156377,0.6613205707775118,0.2994844672509577,0.6775766385619625,0.0524254302557402,0.17000252715590747,0.08279853272694337,0.7976964895507386,0.2586232578193133,0.5407438889952781,0.6549528116330233,0.6585051307117313,0.6694116153560906,0.11112823968034669,0.6929745773941535,0.7625513030032638,0.30362664611197454,0.993784304510347,0.5039916460429245,0.30495787424884246,0.922660665443317,0.5822732264340533,0.9978645334148264,0.8966122463756533,0.745005421888669,0.40052658053165513,0.1727340595716318,0.21089643062392915,0.41589151111196954,0.21585434572326423,0.8212737710293209,0.895693583478337,0.1814341729865825,0.19243925728357913,0.5249868201575476,0.23593429840540492,0.25936553278656527,0.13798700336230074,0.09717785695559777,0.5745907963176073,0.6079362603124165,0.8535843809645556,0.325915063211921,0.7878862046579876,0.710991150012541,0.33941332216043274,0.671156071596836,0.8025884125600424,0.015486353786243634,0.40600149308076705,0.9545291636519525,0.3101664816405325,0.16285335602143713,0.08193663493110792,0.6321133051709148,0.33324381318595475,0.05323827043132834,0.700759092635583,0.08080693076042611,0.3369350769502475,0.5190947234732006,0.2243534811686967,0.5104501621908052,0.3554355426136493,0.12142208071098515,0.3513549797305152,0.9311402509631613,0.8545331855812813,0.894939905279927,0.03778353645036603,0.7235491785936249,0.16761646130080254]

**Comment by mickdelaney** [comment]
@ilovesoup does the above make sense to you ? is it something you think might be wrapped into the TI* products ?

**Comment by mickdelaney** [comment]
thanks for clarifying. 
regards
