### ISSUE TITLE
Support spark-sql query TiSpark?

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tispark#302]

**Comment by ilovesoup** [comment]
There is a tispark-sql script 
https://github.com/pingcap/tispark/tree/master/core/scripts
Copy it to your bin directory and you should be able to use as spark-sql script but with tidb data mounted automatically.

**Comment by duckstar2** [comment]
when starting multi spark-sql,only the first session is successful ,others occur error:Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database /data/tidb/deploy/spark/bin/metastore_db.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)

**Comment by ilovesoup** [comment]
@duckstar2 Sorry for being late response. It's Spark's default behavior. Default implementation is using Derby database which allows only one user at a time. You can change a directory to start spark or add hive-site.xml and config metastore db to Mysql(TiDB)
