### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Mvpanswer7** [pingcap/tispark#303]
执行mvn clean install -Dmaven.test.skip=true  
get   

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (clone proto files) on project tikv-client: Command execution failed. Cannot run program "/home/work/app/github/tispark/tikv-client/scripts/proto.sh" (in directory "/home/work/app/github/tispark/tikv-client"): error=2, No such file or directory -> [Help 1]

**Comment by birdstorm** [comment]
hi, @Mvpanswer7

Thanks for your feedback. Please check if you have access to `/home/work/app/github/tispark/tikv-client/scripts/proto.sh`. Could you kindly run `git status` and  `git log --oneline | head -n 5` in `tispark` folder?

**Comment by ilovesoup** [comment]
@Mvpanswer7 Anything further needed from our side?

**Comment by ilovesoup** [comment]
I will close this for now. @Mvpanswer7 If further update you have, you might reopen this.
