### ISSUE TITLE
How to query table with database name？

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tispark#308]
We can query table in this way：
    ti.tidbMapDatabase("test")
    spark.sql("select * from tidb_test").show
but we can't query table with database name:
    spark.sql("select * from test.tidb_test").show
 this query will throw exception :
org.apache.spark.sql.AnalysisException: Table or view not found: `test`.`tidb_test`; line 1 pos 14;
'Project [*]
+- 'UnresolvedRelation `test`.`tidb_test`

If we can't query with database name , how can we join tow table in different database?

**Comment by birdstorm** [comment]
Hi, @lizhenhuan 

Thanks for your feedback. If any two tables you are using don't have duplicate table names, you may simply use:
```
ti.tidbMapDatabase("test1")
ti.tidbMapDatabase("test2")
```
and query:
```
spark.sql("select * from table1, table2").show
```
where `table1` and `table2` originate from `test1` and `test2` respectively.

If there are duplicate table names, you may use:
```
ti.tidbMapDatabase("test1", dbNameAsPrefix = true)
ti.tidbMapDatabase("test2", dbNameAsPrefix = true)
```
where the corresponding table names for `table1` will be `test1_table1` and `test2_table1`.

**Comment by lizhenhuan** [comment]
get it. thank you very much

**Comment by yixinGod** [comment]
hi ! please tell me ,how to connect the database_name and database_name ?
I try database_name.database_name but can not.

error like this:

scala> ti.tidbMapDatabase("prod_ods",dbNameAsPrefix = true)

scala> spark.sql("select id from trade limit").show
+---------+
|       id|
+---------+
|551191467|
|551191468|
|551191469|
|551191470|
|551191471|
|551191472|
|551191473|
|551191474|
|551191475|
|551191476|
|551191477|
|551191478|
|551191479|
|551191480|
|551191481|
|551191482|
|551191483|
|551191484|
|551191485|
|551191486|
+---------+
only showing top 20 rows


scala> spark.sql("select id from prod_ods.trade limit").show
18/04/27 11:24:12 WARN ObjectStore: Failed to get database prod_ods, returning NoSuchObjectException
org.apache.spark.sql.AnalysisException: Table or view not found: `prod_ods`.`trade`; line 1 pos 15;
'Project ['id]
+- 'UnresolvedRelation `prod_ods`.`trade`, limit

**Comment by birdstorm** [comment]
@yixinGod Hi.
If you use `dbNameAsPrefix = true`, your table should be `prod_ods_trade`, i.e., database name and table name are separated by underline. That is because spark view does not support dot in view name.

**Comment by yixinGod** [comment]
get ,thanks

**Comment by birdstorm** [comment]
@yixinGod My pleasure. Feel free to address more issues if you encounter any difficulties!
