### ISSUE TITLE
Plan to add 2pc for tikv-client?

### ISSUE THREAD

**Issue by lerencao** [pingcap/tispark#323]
Is there any plan to support 2pc for tikv-client ?
It will open many opportunities for tikv in Java world, like a underlining storage for janusgraph.

**Comment by ilovesoup** [comment]
For short term (within this year), there is no plan for it. For now, most user dump data into TiDB via Spark JDBC connector. The performance overhead is on transaction related stuff and manually 2PC on Java side has no improvement on it. But we do have plan to allow Spark dump directly to rocksDB, but without transaction support.

**Comment by lerencao** [comment]
Thanks for the replay. Get your points.

What's I mean is a full tikv client(without tidb stuff) with transaction support, which I think can be modeled similar  to [the implementation in tidb](https://github.com/pingcap/tidb/tree/master/store/tikv).

If there's not plan for it, I'm going to start this.

Thank you again.

**Comment by ilovesoup** [comment]
There is no near plan for it and you are welcome to take it :)

**Comment by ilovesoup** [comment]
@lerencao We are planning on related features. Do you have any progress on 2PC part? If so, we can cooperate on it.

**Comment by lerencao** [comment]
Nope...
The 2PC impl in tidb repo was coupled with tidb specific codes, and I had some issues on mapping Go `Context` concept to Java world. 

After writing some trivial classes in [my branch](https://github.com/lerencao/tispark/tree/feature/2pc), I left it decay... :)
