### ISSUE TITLE
Count(column) is wrongly translated to count(1)

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#338]
select count(L_SUPPKEY) from lineitem where L_ORDERKEY < 1115000 
generates a plan as 
== Physical Plan ==
*HashAggregate(keys=[], functions=[sum(count(1)#456L)])
+- Exchange SinglePartition
   +- *HashAggregate(keys=[], functions=[partial_sum(count(1)#456L)])
      +- TiDB CoprocessorRDD{[table: lineitem] [Index: l_orderkey_idx] , Columns: [L_ORDERKEY], Aggregates: Count(1)} EstimatedCount:8724095.5

Which was turned into index only search and is wrong.

**Comment by birdstorm** [comment]
I think the `L_SUPPKEY` might be `NON NULL`. So this translation is done by spark and is correct.
