### ISSUE TITLE
 tispark 在已有 cdh 版本的yarn集群中如何使用

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tispark#352]
PingCAP 团队你们好：
      请问一下，如果已有一个 spark yarn 的集群。  tispark 如果对接使用呢？

**Comment by shenlijungg** [comment]
另外  遇到一个奇怪问题，在用tidb sql 查询的时候   ，因为SQL执行几乎将PD1, TiDB1   所在服务器的内存耗尽 大概还剩1g  的时候报错了，然后日志报错中有 drop region.  4000端口也连不上了。请问遇到这种 情况 如何恢复！

**Comment by birdstorm** [comment]
现在tispark要求spark版本2.1，jdk版本1.8以上，spark2.2及2.3的支持正在进行中

关于内存耗尽的问题，请问是报错了oom还是别的错误，可以贴一下log吗？另外executor和driver的memory设置了多少？因为tikv和tidb自己也占用一部分内存，所以如果和spark部署在同一个机器上需要预留一部分内存。

**Comment by shenlijungg** [comment]
import org.apache.spark.sql.TiContext
val ti = new TiContext (spark)
ti.tidbMapDatabase ("tpch")

After that you can call Spark SQL directly:

spark.sql ("select count (*) from lineitem")    换成 spark.sql ("insert 语句")  不行吗？

**Comment by birdstorm** [comment]
目前不行，你需要使用jdbc导入数据，参考[this document](https://github.com/pingcap/tispark/blob/master/docs/userguide.md#load-spark-dataframe-into-tidb-using-jdbc)

**Comment by shenlijungg** [comment]
感谢支撑
