### ISSUE TITLE
tikv-client 提供一个insert, update, delete 实例？

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#356]
准备在tispark 上实现insert, update, delete 操作，tikv-client 提供一个insert, update, delete 实例？ 方便入门学习

**Comment by ilovesoup** [comment]
TiKV暂时还没有直接实现insert/update/delete操作。现在TiSpark的插入删改等是通过JDBC完成的，因为我们暂时没有意向通过Spark节点完成分布式事务。

**Comment by ilovesoup** [comment]
清理问题，先关闭了，如果还有问题请再打开它。谢谢
