### ISSUE TITLE
使用spark-shell做测试时，报警告信息，非常不爽！

### ISSUE THREAD

**Issue by aesirteam** [pingcap/tispark#362]
zhongkui:/opt/spark$ ./bin/spark-shell
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark/jars/tispark-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
18/06/15 16:22:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/06/15 16:22:07 WARN Utils: Your hostname, zhongkui-ThinkPad resolves to a loopback address: 127.0.1.1; using 10.196.230.4 instead (on interface enp0s31f6)
18/06/15 16:22:07 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
18/06/15 16:22:13 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Spark context Web UI available at http://10.196.230.4:4040
Spark context available as 'sc' (master = spark://10.196.130.83:7077,10.196.130.82:7077, app id = app-20180615162208-0004).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/
         
Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_171)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
ti: org.apache.spark.sql.TiContext = org.apache.spark.sql.TiContext@4d4337f9

scala> 18/06/15 16:23:14 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 1, new store id 4
18/06/15 16:23:14 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 4, new store id 0
18/06/15 16:23:15 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 4, new store id 1
18/06/15 16:23:24 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 1, new store id 0
18/06/15 16:23:25 WARN KVErrorHandler: Stale command for region [{Region[4013] ConfVer[3] Version[6] Store[1] KeyRange[]:[116,128,0,0,0,0,0,0,7]}]
18/06/15 16:23:25 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 1, new store id 0
18/06/15 16:23:34 WARN KVErrorHandler: NotLeader Error with region id 4013 and store id 1, new store id 4
scala> ti.tidbMapDatabase("TPCH_001")

scala> spark.sql("select count(*) from lineitem").show
+--------+
|count(1)|
+--------+
|   60175|
+--------+

结果是正确的，但是不停打印，非常不爽！请解决！！！！

**Comment by Novemser** [comment]
可以调整一下LogLevel
```scala
scala> sc.setLogLevel("ERROR")
```

**Comment by aesirteam** [comment]
现在是一个项目的技术评估阶段，忽略这个警告，对系统稳定性有影响吗？还是有点担心

**Comment by aesirteam** [comment]
@Novemser 按您说的将日志等级调至ERROR, 但ti.tidbMapDatabase("TPCH_001")大约5秒左右，这正常吗？

**Comment by Novemser** [comment]
@aesirteam 
1. 您在使用的时候TiKV那边压力大吗?这个警告一般是KV压力过大造成的
2. 5秒左右是正常的,MapDatabase中需要收集一些统计信息

**Comment by Novemser** [comment]
@aesirteam 
两种加快映射表速度的方案
1. 可以在`ti.tidbMapDatabase`的时候关闭统计信息载入:`ti.tidbMapDatabase("TPCH_001", autoLoadStatistics = false)`
2. 如果只需要映射数据库中的部分表不需要映射全部的表,可以考虑使用`tidbMapTable`接口,如`ti.tidbTable("TPCH_001", "lineitem")`

详见
https://github.com/pingcap/tispark/blob/master/docs/userguide.md#statistics-information
https://github.com/pingcap/tispark/blob/master/core/src/main/scala/org/apache/spark/sql/TiContext.scala

**Comment by ilovesoup** [comment]
@aesirteam 实际上，TiKV和PD会不断迁移Leader的位置（因为数据被搬迁或者因为PD决定调度热点等等原因），所以NotLeader并不算真正意义上的错误。TiSpark需要做的是刷新Leader所在的位置重新发起请求。
但是如果NotLeader是因为压力过大而不断迁移甚至TiKV因为压力过心跳暂停等的话，那就要重新审视leader迁移的原因。这点可以通过监控看到。

**Comment by ilovesoup** [comment]
@aesirteam 我会先关闭这个问题，如果还有其他疑问，可以重新打开它或者另外再提。
