### ISSUE TITLE
关于TiContext的一个报错，代码修改conf并未生效

### ISSUE THREAD

**Issue by aesirteam** [pingcap/tispark#363]
zhongkui:/opt/spark$ spark-shell --master spark://10.196.130.82:7077,10.196.130.83:7077
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark/jars/tispark-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
18/06/15 18:41:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/06/15 18:41:38 WARN Utils: Your hostname, zhongkui-ThinkPad resolves to a loopback address: 127.0.1.1; using 10.196.230.4 instead (on interface enp0s31f6)
18/06/15 18:41:38 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
18/06/15 18:41:43 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Spark context Web UI available at http://10.196.230.4:4040
Spark context available as 'sc' (master = spark://10.196.130.82:7077,10.196.130.83:7077, app id = app-20180615184139-0002).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/
         
Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_171)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.sparkContext.getConf.set("spark.tispark.pd.addresses","10.196.130.89:2379")
res1: org.apache.spark.SparkConf = org.apache.spark.SparkConf@fdf029a

scala> print(res1.toDebugString)
hive.metastore.warehouse.dir=file:/opt/spark/spark-warehouse
spark.app.id=app-20180615184139-0002
spark.app.name=Spark shell
spark.driver.host=10.196.230.4
spark.driver.port=37733
spark.executor.id=driver
spark.home=/opt/spark
spark.jars=
spark.master=spark://10.196.130.82:7077,10.196.130.83:7077
spark.repl.class.outputDir=/tmp/spark-a51b3762-2ea9-4236-b14f-86e0fc42a0ad/repl-3a8b1e13-e8a8-42aa-94bd-2778b1da3625
spark.repl.class.uri=spark://10.196.230.4:37733/classes
spark.sql.catalogImplementation=hive
spark.submit.deployMode=client
spark.tispark.pd.addresses=10.196.130.89:2379
scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
java.util.NoSuchElementException: spark.tispark.pd.addresses
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.SparkConf.get(SparkConf.scala:243)
  at com.pingcap.tispark.TiUtils$.sparkConfToTiConf(TiUtils.scala:182)
  at org.apache.spark.sql.TiContext.<init>(TiContext.scala:36)
  ... 48 elided

**Comment by birdstorm** [comment]
spark.tispark.pd.addresses is not configurable in spark session. You should configure it in spark-defaults.conf, and it will be effective after restarting spark.

**Comment by birdstorm** [comment]
@aesirteam Hi, is this problem fixed?

**Comment by ilovesoup** [comment]
Please reopen it if needed.
