### ISSUE TITLE
tispark sql问题请教

### ISSUE THREAD

**Issue by carr123** [pingcap/tispark#371]
你好，用tispark 执行sql查询的时候不能使用索引么？  是不是tispark sql执行时采用并行全表扫描？

因为我对索引字段用tispark sql查询速度慢很多， 要mysql客户端查询很快。

初学，望指教，谢谢

**Comment by birdstorm** [comment]
Hi, @carr123.

First of all, please confirm that you have set `spark.tispark.plan.allow_index_read` to true. This is essential because its default setting is false. You may refer to more configuration from [this document](https://github.com/pingcap/tispark/blob/master/README.md#configuration)

Anyhow, if you have index information on your data, TiSpark _MAY_ choose to use index according to its CBO.

Hope these would help. :)

**Comment by birdstorm** [comment]
Hi, @carr123 .

The 10+ seconds that you noticed is an overhead time consumption that would not affect following queries. You may execute multiple queries after you have finished `tidbMapDatabase` operation, and execution time would be the time of the sql statement itself.

Also, could you state your spark environment as well? How many spark nodes are you using?

If the efficiency still does not meet your expectation, would you kindly send us the SparkPlan by `spark.sql("...").explain` so we could look into this?

**Comment by carr123** [comment]
@birdstorm 
I test 2  SQL query, 

./bin/spark-submit  test.py --num-executors 4  --driver-memory 2G

4 spark workers running on 2 nodes, each 1core, 1GB RAM used.
tikv-server running on the same 2 nodes.


1. Parsing command: select userid,count(factor) as t from train group by userid order by t desc limit 5
== Physical Plan ==
TakeOrderedAndProject(limit=5, orderBy=[t#34L DESC NULLS LAST], output=[userid#18,t#34L])
+- *HashAggregate(keys=[userid#18], functions=[sum(count(factor#19)#40L)])
   +- Exchange hashpartitioning(userid#18, 200)
      +- *HashAggregate(keys=[userid#18], functions=[partial_sum(count(factor#19)#40L)])
         +- TiDB CoprocessorRDD{[table: train] , Columns: [factor], [userid], Aggregates: Count([factor]), First([userid]), Group By: [[userid] ASC]}

time taken
run sparksql task :  271s (not including map database)
from mysql client : 242s

2. SparkSqlParser: Parsing command: select count(*) from train
== Physical Plan ==
*HashAggregate(keys=[], functions=[sum(count(1)#38L)])
+- Exchange SinglePartition
   +- *HashAggregate(keys=[], functions=[partial_sum(count(1)#38L)])
      +- TiDB CoprocessorRDD{[table: train] [Index: userid] , Aggregates: Count(1)} EstimatedCount:40315849

time taken
run sparksql task :  54s (not including map database)
from mysql client : 25s

**Comment by ilovesoup** [comment]
Spark的并发模型和TiDB有不同，你可以认为TiSpark的并发完全看spark executor的core数，而上面的测试场景一共2个core，很大程度上会比TiDB的goroutine并发慢很多，因为一次只计算2个region。所以扩大并发或者手动调整一个core多少并发读取TiKV也可以缓解
spark.tispark.task_per_split = 2或者4

另外，TiDB在聚合可以下推的场合，如果没有更进一步需要shuffle数据的计算（比如join），那么速度并不会比TiSpark慢，哪怕给予同样的core数，因为大部分计算在TiKV完成，而TiDB的并发模型比Spark要灵活得多。

因此，如果是上述测试的场合，给予Spark足够的core，会得到和TiDB近似的速度，但是不会更快。如果是更复杂的查询（比如多表join），TiSpark会更快。

**Comment by carr123** [comment]
thanks a lot
