### ISSUE TITLE
tithrift server udf not work

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tispark#381]
新建一个纯净的tispark 1.0环境
测试spark-shell是否可以使用udf
./spark-shell --master local[*] --jars /data/jars/udfs-1.0-SNAPSHOT.jar 
spark.sql("CREATE FUNCTION msk_hash AS 'com.bkjk.udfs.MskHash' ")
spark.sql("select msk_hash('as')").show
+--------------------+
|default.msk_hash(as)|
+--------------------+
|6e001fee7b633a388...|
+--------------------+

测试tithrift server是否可以使用udf
启动tithrift server，使用beeline连接，执行
select msk_hash('as');
Error: org.apache.spark.sql.AnalysisException: Undefined function: 'msk_hash'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7 (state=,code=0)

tithrift 无法使用sql create 出来的udf，udaf以及udtf函数。

**Comment by birdstorm** [comment]
have you added jar in thrift server?
try 
```sql
add jar /data/jars/udfs-1.0-SNAPSHOT.jar;
CREATE FUNCTION msk_hash AS 'com.bkjk.udfs.MskHash' ;
```

**Comment by lizhenhuan** [comment]
spark-shell

spark.stop
import org.apache.spark.sql.SparkSession
val hive = SparkSession.builder().enableHiveSupport().getOrCreate
hive.sql("drop function msk_hash")
hive.sql("CREATE FUNCTION msk_hash AS 'com.bkjk.udfs.MskHash' ")
hive.sql("select msk_hash('dsfgh')").show

start tithrift-server
beeline connect tithrift-server
select msk_hash('dsfgh')

it is ok now.
