### ISSUE TITLE
spark.tispark.pd.addresses 参数能够通过ticontext 参数传递

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#389]
tispark 没有权限校验，考虑安全性，避免用户通过spark conf 获取address，spark.tispark.pd.addresses 参数能够通过ticontext 传递进去。

**Comment by wangqiaoshi** [comment]
+1

**Comment by birdstorm** [comment]
@melin @wangqiaoshi 

You could as well pass `spark.tispark.pd.address` through Spark configuration. e.g., when you are initializing your SparkSession.

In any case, the address should be set before the session was initialized.
