### ISSUE TITLE
tispark与mysql客户端查询同一条sql得到的结果不一致

### ISSUE THREAD

**Issue by powqabc** [pingcap/tispark#395]
同一条sql通过tispark跟mysql客户端查询的结果不一致
![image](https://user-images.githubusercontent.com/10123620/42871964-2eb41c60-8aae-11e8-8564-665da6701563.png)
![image](https://user-images.githubusercontent.com/10123620/42871977-3765d6d2-8aae-11e8-9537-a4111b8cd051.png)
![image](https://user-images.githubusercontent.com/10123620/42871997-415bb882-8aae-11e8-96cc-e3b4f71060e0.png)

**Comment by birdstorm** [comment]
Hi, @powqabc.  Thanks for your feedback.

可否提供一下user_overall_monthly_stat的表结构？我可以尝试复现一下。

**Comment by ilovesoup** [comment]
From user, 数据类型是decimal(9,4)

**Comment by ilovesoup** [comment]
能重现，看起来是个decode错误。

**Comment by ilovesoup** [comment]
https://github.com/pingcap/tispark/pull/401

**Comment by ilovesoup** [comment]
这是一个codec错误，在某些branch下，由于java没有unsigned且我们代码没有正确处理会产生问题。

**Comment by birdstorm** [comment]
@melin Is this issue resolved?

**Comment by melin** [comment]
已经解决了，谢谢！
