### ISSUE TITLE
通过tispark查询的时候出现Handle region task failed

### ISSUE THREAD

**Issue by powqabc** [pingcap/tispark#411]
任务场景大概是下面这样的
![image](https://user-images.githubusercontent.com/10123620/43509304-e18604e2-95a4-11e8-9094-114ddcd6288e.png)
每次select出一天的数据，然后做一些处理之后写入到hive表里。每次循环连续跑十几天数据之后就报下个那个错误。然后从错误的那个日期开始跑又是可以的，然后跑个十几天数据之后又出错
![image](https://user-images.githubusercontent.com/10123620/43509383-199c6fa6-95a5-11e8-9daa-04d0034ae7f1.png)
![image](https://user-images.githubusercontent.com/10123620/43509389-2444d33a-95a5-11e8-94c7-08655173c7cd.png)
![image](https://user-images.githubusercontent.com/10123620/43509404-2d164a0c-95a5-11e8-9005-9b96875f263e.png)
![image](https://user-images.githubusercontent.com/10123620/43509415-34990422-95a5-11e8-884f-3cf3db4839b8.png)

**Comment by birdstorm** [comment]
@powqabc Thanks for your feedback. I am looking into this problem.
