### ISSUE TITLE
TiSpark

### ISSUE THREAD

**Issue by 19913144245** [pingcap/tispark#429]
我们搭建了测试的TiDB集群；
现在有另外的三台spark集群。怎么才能让spark成为Tispar可以访问PD。
现在报错：failed to get member from pd server.
io.grpc.StatusRuntimeException: UNAVAILABLE

**Comment by birdstorm** [comment]
You may refer to this [document](https://github.com/pingcap/tispark/blob/master/docs/userguide.md#demo)

Simply add pd address to your `spark-default.conf` or define it when creating your SparkSession.

**Comment by 19913144245** [comment]
Thank you for your reply.
And I have another question.
Because my spark and tidb cluster are not together, access to PD requires username and password. Where is this configured?

**Comment by birdstorm** [comment]
Hi @19913144245 , I don't quite understand what username and password you are referring to because PD does not have any authentication. If you mean to ssh to PD, you might need to configure your ssh configuration so that you can access PD cluster via ssh, and that is not included in TiSpark configuration.

**Comment by 19913144245** [comment]
If the PD is not authenticated, is it possible to access the data as long as the PD address and port are known? Isn't that dangerous?
Maybe I didn't express myself clearly. I am now the two cluster, one TiDB, one Spark. How can spark access TiDB data?
I have read the official document, and, as I operate, I made a mistake when I implemented Val Ti = new TiContext (spark).

**Comment by 19913144245** [comment]
没有 Spark 集群的部署方式

如果没有使用中的 Spark 集群，推荐使用 Saprk Standalone 方式部署。这里简单介绍下 Standalone 部署方式。如果遇到问题，可以去官网寻求帮助；也欢迎在我们的 GitHub 上提 issue。

下载安装包并安装

你可以在这里下载 Apache Spark。

对于 Standalone 模式且无需 Hadoop 支持，则选择 Spark 2.1.x 且带有 Hadoop 依赖的 Pre-build with Apache Hadoop 2.x 任意版本。如有需要配合使用的 Hadoop 集群，则选择对应的 Hadoop 版本号。你也可以选择从源代码自行构建以配合官方 Hadoop 2.6 之前的版本。注意目前 TiSpark 仅支持 Spark 2.1.x 版本。

如果你已经有了 Spark 二进制文件，并且当前 PATH 为 SPARKPATH，需将 TiSpark jar 包拷贝到 ${SPARKPATH}/jars 目录下。

启动 Master

在选中的 Spark Master 节点执行如下命令：

cd $SPARKPATH
./sbin/start-master.sh
在这步完成以后，屏幕上会打印出一个 log 文件。检查 log 文件确认 Spark-Master 是否启动成功。你可以打开 http://spark-master-hostname:8080 查看集群信息（如果你没有改动 Spark-Master 默认 Port Numebr）。在启动 Spark-Slave 的时候，也可以通过这个面板来确认 Slave 是否已经加入集群。

启动 Slave

类似地，可以用如下命令启动 Spark-Slave 节点：

./sbin/start-slave.sh spark://spark-master-hostname:7077
命令返回以后，即可通过刚才的面板查看这个 Slave 是否已经正确地加入了 Spark 集群。在所有 Slave 节点重复刚才的命令。确认所有的 Slave 都可以正确连接 Master，这样你就拥有了一个 Standalone 模式的 Spark 集群。

一个使用范例

假设你已经按照上述步骤成功启动了 TiSpark 集群，下面简单介绍如何使用 Spark SQL 来做 OLAP 分析。这里我们用名为 tpch 数据库中的 lineitem 表作为范例。

假设你的 PD 节点位于 192.168.1.100，端口为 2379，在$SPARK_HOME/conf/spark-defaults.conf加入：

spark.tispark.pd.addresses 192.168.1.100:2379
然后在 Spark-Shell 里输入下面的命令：

import org.apache.spark.sql.TiContext

val ti = new TiContext(spark)              这一步会报错。

ti.tidbMapDatabase("tpch")

仅仅是添加了TiSpark jar 就可以访问PD吗？不行吧。。  配置文件也仅仅是 IP 和端口。

**Comment by birdstorm** [comment]
> 仅仅是添加了TiSpark jar 就可以访问PD吗？

前提条件：Spark集群可以通过pdaddress访问PD集群。
如果两个都不在一个网络里，那肯定不行。

**Comment by 19913144245** [comment]
好的。谢谢了。

**Comment by longxibendi** [comment]
你俩中英文混杂交流，真逗。
It's funny how you two communicate in Chinese and English。

**Comment by birdstorm** [comment]
Hi, @longxibendi , I would like to comment with English because this is not a product only for Chinese users, other users might find same question and look for solutions from Github issues. However I also find expressing in native language is better for understanding sometimes.

@19913144245 , If your problem is solved, I could close this issue now. :)
