### ISSUE TITLE
TiSpark 

### ISSUE THREAD

**Issue by 19913144245** [pingcap/tispark#433]
Hello:
Now I have 4 machines locally, and I have built a simple test TiDB cluster. Business as usual.
Now I want to use TiSpark to test.
According to the document, I can build Spark in these 4 machines and deploy them to TiSpark.
The default deployment is in the TiDB instance deployment directory, with no Spark directory. What should I am going to do?
Now I have built standalone mode Spark on 3 other machines. Tispark-0.1.0-SNAPSHOT-jar-with-dependencies is also deployed. What do we need to do for the rest?

Welcome to reply.

**Comment by ilovesoup** [comment]
In spark-defaults.conf add your pd addresses like this:
spark.tispark.pd.addresses 192.186.1.10:2379,192.186.1.11:2379,192.186.1.12:2379 
addresses are comma separated.
Start spark shell and follow guide here
https://github.com/pingcap/tispark#quick-start

**Comment by 19913144245** [comment]
hello:
If there is another Spark cluster, do you want to deploy the Spark cluster information in the inventory.ini of the central computer, and then add spark. tispark. pd. addresses 192.186.1.10:2379, 192.186.1.11:2379, 192.186.1.12:2379 to the Spark?
If the TiDB cluster starts, only need to decompress the installation according to official website.

**Comment by ilovesoup** [comment]
Sorry for late responding. I don't quite understand your point.
You can reach me at maxiaoyu@pingcap.com and we might communicate via something like wechat.
