### ISSUE TITLE
How does TiSpark decide on number of Tasks

### ISSUE THREAD

**Issue by Guru107** [pingcap/tispark#457]
Currently, I am using TiSpark built for Spark 2.3. I have set the `spark.sql.shuffle.partitions` to 10 but still, the number of tasks go to around 900. It eventually leads to StackOverflow Error. How does TiSpark decide on number of task.

**Comment by birdstorm** [comment]
Hi @Guru107 

`spark.sql.shuffle.partitions` configures the number of partitions that are used when shuffling data for joins or aggregations. If you task is not a join or aggregation, this configuration won't take effect.

If you are actually using a join, would you please provide a simple reproducible script so that we could trace this?

TiSpark does not decide on the number of task, the number of all tasks is decided by Spark itself. While TiSpark provides multiple configurations for scan concurrency when reading data from TiDB, please note that they will not change the number of tasks, and will only restrict the maximal threads reading data in one task.

**Comment by Guru107** [comment]
I have a Spark Application which does a join on 11 tables. Basically to denormalise a fact table by joining with all dimension tables.  Joining happens on Spark. 

1. I retrieve the fact table from tikv based on a time range.
2. Get all the matching rows from all dimension tables based on filters pushed down extracted from the fact table.
3. Left join all the retrived tables with the fact table.

A code snippet of what I am trying to achive. Currently the batch is just 15 min number of rows are around 10,000 to 15,000 in fact table.

While querying the `factTable` it generates around 900 task. Considering only 10000 to 15000 records it seems too much. 
```
val factTable = sparkSession.sql("select * from fact_table where last_modified_time between lowerBound and higerbound") 

//Get only the rows required from a dimension tables by generating a where clause
//This generates dim1_id=122 OR dim1_id=123 OR dim1_id=124 OR ...

val dim1TableFilter = factTable.map(fact => s"dim1_id = ${fact.dim1_id}").dropDuplicates().reduce(_+" OR "+_)

val dim1Table = sparkSession.sql(s"select col1,col2,col3.... from dim1Table where ${dim1TableFilter}")

val dim2TableFilter = factTable.map(fact => s"dim2_id = ${fact.dim2_id}").dropDuplicates().reduce(_+" OR "+_)
val dim2Table = sparkSession.sql(s"select col1,col2,col3.... from dim2Table where ${dim2TableFilter}")

val dim3TableFilter = factTable.map(fact => s"dim3_id = ${fact.dim3_id}").dropDuplicates().reduce(_+" OR "+_)
val dim3Table = sparkSession.sql(s"select col1,col2,col3.... from dim3Table where ${dim3TableFilter}")
...
....
...... so on 

// Finally join fact tables with dimension tables

val denormalisedTable = factTable.join(dim1Table,Seq("dim1_id"))
	.join(dim2Table,Seq("dim2_id"))
	.join(dim3Table,Seq("dim3_id"))
	.join(dim4Table,Seq("di4_id"))
	.join(dim5Table,Seq("dim5_id"))
	.join(dim6Table,Seq("dim6_id"))
	.join(dim7Table,Seq("dim7_id"))
	.join(dim8Table,Seq("dim8_id"))
	.join(dim9Table,Seq("dim9_id"))
	.join(dim10Table,Seq("dim10_id"))
	.join(dim11Table,Seq("dim11_id"))

// Push the record to Kafka
 denormalisedTable
      .select(to_json(keyColumns).as("key"), to_json(struct(col1,col2,col3...)).as("value"), current_timestamp().as("timestamp"))
      .selectExpr("CAST(key as STRING)", "CAST(value as STRING)", "CAST(timestamp as LONG)")
      .write
      .format("kafka")
      .options(PropertiesParser.getKafkaConf())
      .option("topic", topicName)
      .save()
```

**Comment by birdstorm** [comment]
@Guru107 Which stage generated 900 tasks?

**Comment by birdstorm** [comment]
@Guru107 How about caching your factTable since you are using quite frequently?

**Comment by Guru107** [comment]
@birdstorm I am doing that.

**Comment by birdstorm** [comment]
I will take a look at this :)

**Comment by birdstorm** [comment]
Well, can you provide the schema of `fact_table`?

**Comment by Guru107** [comment]
@birdstorm Schema for `fact_table`
```
root
 |-- Col1: long (nullable = false)
 |-- Col2: long (nullable = false)
 |-- Col3: string (nullable = true)
 |-- Col4: long (nullable = true)
 |-- Col5: string (nullable = true)
 |-- Col6: string (nullable = true)
 |-- Col7: long (nullable = true)
 |-- Col8: string (nullable = true)
 |-- Col9: long (nullable = true)
 |-- Col10: string (nullable = true)
 |-- Col11: long (nullable = true)
 |-- Col12: string (nullable = true)
 |-- Col13: decimal(10,2) (nullable = true)
 |-- Col14: string (nullable = true)
 |-- Col15: long (nullable = false)
 |-- Col16: string (nullable = true)
 |-- Col17: string (nullable = true)
 |-- Col18: string (nullable = true)
 |-- Col19: string (nullable = true)
 |-- Col20: string (nullable = true)
 |-- Col21: decimal(10,2) (nullable = true)
 |-- Col22: decimal(10,2) (nullable = true)
 |-- Col23: decimal(10,2) (nullable = true)
 |-- Col24: decimal(10,2) (nullable = true)
 |-- Col25: string (nullable = true)
 |-- Col26: string (nullable = true)
 |-- Col27: string (nullable = true)
 |-- Col28: decimal(10,2) (nullable = true)
 |-- Col29: decimal(10,2) (nullable = true)
 |-- Col30: decimal(10,2) (nullable = true)
 |-- Col31: decimal(10,2) (nullable = true)
 |-- Col32: decimal(10,2) (nullable = true)
 |-- Col33: decimal(10,2) (nullable = true)
 |-- Col34: long (nullable = false)
```

`factTable.rdd.partitions.size` is 991

**Comment by birdstorm** [comment]
@Guru107 you might use `factTable.repartition(xxx)` to repartition your data. TiSpark splits tasks by `regions` from TiKV. It means that there are 900+ regions involved.
