### ISSUE TITLE
Real time monitoring TiDB

### ISSUE THREAD

**Issue by 19913144245** [pingcap/tispark#462]
How to monitor the change of a table in TiDB database in real time, for example, insert or update.

**Comment by birdstorm** [comment]
Can you provide more details for your issue?

**Comment by 19913144245** [comment]
1.We want to monitor database increments and use incremental data in SparkStreaming computing.
2.Can the operation of TiDB-Binlog be more detailed?

**Comment by ilovesoup** [comment]
@19913144245 does this answer your question?
