### ISSUE TITLE
Streaming Coprocessor not correctly handle the split or merge

### ISSUE THREAD

**Issue by Handora** [pingcap/tispark#477]
Streaming Coprocessor does not correctly handle the split or merge.

What the streaming coprocessor do now is simply handling it to the iterator 
and ignore the split/merge if wrong, we should correct for use of streaming coprocessor

**Comment by ilovesoup** [comment]
Please remove streaming conf item for now as it is now matured enough for use. Also please sync with TiDB team to see if they are using it as default. If so, we need to do a thorough test and fix remaining issues.
