### ISSUE TITLE
only jdk1.8 or higher? 

### ISSUE THREAD

**Issue by luyee** [pingcap/tispark#48]
it  seems  tikv-client-lib-java  must 1.8

**Comment by ilovesoup** [comment]
Yes. The client part of project uses lambda and some stream api only available on JDK 1.8 and newer.  And start from Spark 2.2, JDK 1.7 support is dropped. So we consider it not a big problem.
Are you using jdk 7 in your current spark cluster?

**Comment by luyee** [comment]
yes .we use  Cloudera Manager,All services run 1.7 now

**Comment by ilovesoup** [comment]
For upgrading, here is a reference.
https://www.cloudera.com/documentation/enterprise/5-3-x/topics/cdh_cm_upgrading_to_jdk8.html
Or you might want to use a standalone cluster for test and decide if to use it and upgrade later.
