### ISSUE TITLE
在保存数据时创建表字符串给text类型

### ISSUE THREAD

**Issue by gudepeng** [pingcap/tispark#481]
在保存数据的时候，自动创建表。然后字符串生成的是text类型，但是如果spark中字符串过长，就会报错，怎么才能让他把这个字段生成longtext类型

**Comment by birdstorm** [comment]
您好，请问能描述的更清晰一些么，最好能有一个简单的重现步骤，谢谢~

**Comment by ilovesoup** [comment]
这个case找过我，用户保存的时候使用的是Spark JDBC Connector，自动创建的时候映射的类型是JDBC内定的规则。对于String使用了直接的Text映射，但是TiDB的Text类型支持最长65535，无法保存用户的数据，需要使用Customized Schema，非常麻烦。
这里我建议保留Issue Open，但是在我们自己做Batch Write的时候用某种方式让用户可以比较方便映射类型，或者自动推演合适的类型。
