### ISSUE TITLE
i used docker-compose to deploy a tidb-clsuter，but when

### ISSUE THREAD

**Issue by yangxu1362850636** [pingcap/tispark#482]
1. i edit the spark-defaults.conf and add a line : spark.tispark.pd.addresses 172.21.0.9:2379
2. ./spark-shell
`
scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
18/11/08 04:09:20 WARN KVErrorHandler: Failed to send notification back to driver since CacheInvalidateCallBack is null in executor node.
18/11/08 04:09:20 WARN KVErrorHandler: Store Not Match happened with region id 6, store id 1
18/11/08 04:09:20 WARN KVErrorHandler: Failed to send notification back to driver since CacheInvalidateCallBack is null in executor node.
`

**Comment by yangxu1362850636** [comment]
`WARN KVErrorHandler: Store Not Match happened with region id 6, store id 1
WARN KVErrorHandler: Failed to send notification back to driver since CacheInvalidateCallBack is null in executor node.`
i don't know how the troubles can be shooting. who can help me ?

**Comment by birdstorm** [comment]
Hi, @yangxu1362850636 . Thanks for your feedback.

Can you provide the version of TiSpark you are using? You may directly use `ti.version`.

I recommend you to use version no less than `1.1` if you are using Spark 2.1, or version no less than `2.0` if you want to try out some new features in Spark 2.3.

**Comment by birdstorm** [comment]
Issue Closed.
