### ISSUE TITLE
有关show columns的需求

### ISSUE THREAD

**Issue by daikon12** [pingcap/tispark#514]
环境：1.TiSpark版本：
![image](https://user-images.githubusercontent.com/8246136/49439127-31411180-f7fb-11e8-9936-9fd581d9275d.png)
2.Spark版本：2.3.2

描述：目前版本对show columns还不支持
![image](https://user-images.githubusercontent.com/8246136/49439194-5b92cf00-f7fb-11e8-8c48-9252bef375df.png)

希望大佬们尽早支持，TiSpark越来越快，越来越稳定

**Comment by birdstorm** [comment]
@daikon12 Thanks for your advice! I will support them soon.
