### ISSUE TITLE
spark-sql --database option does not work

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#524]
Returns NoSuchDatabaseException, because 
Spark-2.3.0:org.apache.spark.sql.hive.thriftserver:SparkSQLCLIDriver.scala:Line 171
```scala
    if (sessionState.database != null) {
      SparkSQLEnv.sqlContext.sessionState.catalog.setCurrentDatabase(
        s"${sessionState.database}")
    }
```
does not use our injected catalog.

**Comment by shiyuhang0** [comment]
close for it is outdated. And the problem is not exist now.
