### ISSUE TITLE
code example of tikv-client doesn't work

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/tispark#698]
The code example in README of `tikv-client` doesn't work now, and need to be updated.

**Comment by zhexuany** [comment]
Can you post the stack trace?  @fredchenbj

**Comment by fredchenbj** [comment]
Like `TiSelectRequest selectRequest = new TiSelectRequest();` , the `TiSelectRequest` was not found, I think it is replace with `TiDAGRequest`. @zhexuany

**Comment by zhexuany** [comment]
Yes. We will fix it as soon as possible. Can I ask why do you want to use `tikv-client` rather than `tispark`?

**Comment by fredchenbj** [comment]
@zhexuany Thx. I am going to use `tispark`, then want to have a deep understanding of `tispark` implementation, and read those source code and example.
