### ISSUE TITLE
We can't use ByteString.copyFromUtf8 any more. 

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tispark#700]
use `ByteString.copyFrom("", StandardCharsets.ISO_8859_1)` instead.

**Comment by birdstorm** [comment]
Internal.UTF8 and StandardCharSet.ISO_8859_1 differs in the decoding of 8-bit UTF-8 characters

**Comment by zhexuany** [comment]
close this issue since it is only problematic when we try to decode an entire key.
