### ISSUE TITLE
tispark read data to hdfs

### ISSUE THREAD

**Issue by wangdabin1216** [pingcap/tispark#908]
I tried to use tispark instead of sqoop to draw numbers from tidb to hdfs. Is there a split-by like sqoop, how to control? Thank you

**Comment by marsishandsome** [comment]
there's no `split-by` in spark as i know, instead you can use `Coalesce`, see https://medium.com/@mrpowers/managing-spark-partitions-with-coalesce-and-repartition-4050c57ad5c4

**Comment by wangdabin1216** [comment]
@marsishandsome 

I tried to use Coalesce=32, but this only controls the output of the program, but my purpose is to read it evenly from the tidb, I am worried about whether there will be data skew or OOM problems.

![image](https://user-images.githubusercontent.com/15032421/60857866-bdf2f880-a23e-11e9-8540-d07f2da5d6e8.png)

**Comment by marsishandsome** [comment]
tispark already solved `data skew` problem, you do not need do anything, just use it.

**Comment by wangdabin1216** [comment]
thx
