### ISSUE TITLE
tispark 2.2 小概率找不到表

### ISSUE THREAD

**Issue by melin** [pingcap/tispark#918]
tispark 2.2 小概率找不到表，重试又正常，之前版本有出现过。
![image](https://user-images.githubusercontent.com/1145830/61103109-58537600-a4a3-11e9-8ba8-c85d2ce000f5.png)

**Comment by birdstorm** [comment]
@melin 能否提供一下大概的概率和重现步骤？对查询的 sql 是否有要求呢？

**Comment by marsishandsome** [comment]
@melin 能否把详细的日志文件发给我们一份？

**Comment by melin** [comment]
查询sql:
![image](https://user-images.githubusercontent.com/1145830/61111795-f30c7e80-a4bc-11e9-8fb8-8a16ce293695.png)
![image](https://user-images.githubusercontent.com/1145830/61111914-454d9f80-a4bd-11e9-9306-a85f836eb1e4.png)

**Comment by birdstorm** [comment]
@melin hi~ 能否看一下是否有 `TiClientInternalException: Error scanning data from region.` 类似的错误？谢谢
