### ISSUE TITLE
Make TiKV-Client a pom child instead of submodule

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#93]
Git submodule seems not quite convenient for our scenario. Almost every time change made in client should be accepted in tispark side. Git submodule makes problem too hard.
We likely turn it into a pom child to avoid submodule modification problems.

**Comment by liancheng** [comment]
Or at least have a script to build TiKV client and install it into the local Maven repository. Otherwise, IDEs couldn't figure out the dependencies easily.

**Comment by Novemser** [comment]
@liancheng Thanks for your advice, currently could refer to this script to build TiKV client and install it into the local Maven repository. https://github.com/pingcap/tispark/blob/master/bin/build-client.sh

**Comment by liancheng** [comment]
@Novemser Thanks! It works great!

**Comment by liancheng** [comment]
@Novemser Ah, it's actually documented in README.md, my fault :)

**Comment by Novemser** [comment]
@liancheng My pleasure : )
