### ISSUE TITLE
Stream and Batch processing

### ISSUE THREAD

**Issue by billhcmus** [pingcap/tispark#937]
Hi all,

I know Spark cluster get data from TiKV, my question (foolish question) is: 
- Is TiSpark support batch processing or stream processing?
- If not, can we do it in the future?

Many thank.

**Comment by billhcmus** [comment]
I think we should have detail documentation about the architecture and some internal workflow about TiSpark 👍

**Comment by marsishandsome** [comment]
hi @billhcmus ,

what do you mean by saying `stream processing`? spark streaming? would you please describe your scenario in detail?
