### ISSUE TITLE
[BUG] Tikv API catalog.getTable failed

### ISSUE THREAD

**Issue by ivorzhou** [pingcap/tispark#942]
**When I  retrieve table meta info by**  
                   session.getCatalog().getTable("test","TRAIN_DIR")

**Exception throws like(Which happen when view exists in this database. I think this is a bug)**
                  

> Exception in thread "main" com.pingcap.tikv.exception.TiClientInternalException: Invalid JSON value for Type TiTableInfo: {"id":84,"name":{"O":"VW_TD","L":"vw_td"},"charset":"utf8mb4","collate":"utf8mb4_bin","cols":[{"id":1,"name":{"O":"START_DATE","L":"start_date"},"offset":0,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":2,"name":{"O":"STOP_DATE","L":"stop_date"},"offset":1,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":3,"name":{"O":"TRAIN_CODE","L":"train_code"},"offset":2,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":4,"name":{"O":"SUBBUREAU_CODE","L":"subbureau_code"},"offset":3,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":5,"name":{"O":"DOUBLE_ID","L":"double_id"},"offset":4,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":6,"name":{"O":"SCHEMA_ID","L":"schema_id"},"offset":5,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":7,"name":{"O":"RUNNING_STYLE","L":"running_style"},"offset":6,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":8,"name":{"O":"RUNNING_RULE","L":"running_rule"},"offset":7,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":9,"name":{"O":"START_STATION_NAME","L":"start_station_name"},"offset":8,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":10,"name":{"O":"END_STATION_NAME","L":"end_station_name"},"offset":9,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":11,"name":{"O":"TRAIN_TYPE_CODE","L":"train_type_code"},"offset":10,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":12,"name":{"O":"TRAIN_CLASS_CODE","L":"train_class_code"},"offset":11,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":13,"name":{"O":"SEAT_TYPES","L":"seat_types"},"offset":12,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":14,"name":{"O":"TRAIN_GROUP","L":"train_group"},"offset":13,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":15,"name":{"O":"BELONG_LINE1","L":"belong_line1"},"offset":14,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":16,"name":{"O":"PRICE_STYLE1","L":"price_style1"},"offset":15,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":17,"name":{"O":"BELONG_LINE2","L":"belong_line2"},"offset":16,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":18,"name":{"O":"PRICE_STYLE2","L":"price_style2"},"offset":17,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":19,"name":{"O":"BELONG_LINE3","L":"belong_line3"},"offset":18,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":20,"name":{"O":"PRICE_STYLE3","L":"price_style3"},"offset":19,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":21,"name":{"O":"BELONG_LINE4","L":"belong_line4"},"offset":20,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":22,"name":{"O":"PRICE_STYLE4","L":"price_style4"},"offset":21,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":23,"name":{"O":"BELONG_LINE5","L":"belong_line5"},"offset":22,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":24,"name":{"O":"PRICE_STYLE5","L":"price_style5"},"offset":23,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":25,"name":{"O":"SERVICE_TYPE","L":"service_type"},"offset":24,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":26,"name":{"O":"PRICE_STYLE","L":"price_style"},"offset":25,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2},{"id":27,"name":{"O":"ORIGIN","L":"origin"},"offset":26,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":2}],"index_info":null,"fk_info":null,"state":5,"pk_is_handle":false,"comment":"","auto_inc_id":0,"max_col_id":27,"max_idx_id":0,"update_timestamp":409936874529619972,"ShardRowIDBits":0,"max_shard_row_id_bits":0,"pre_split_regions":0,"partition":null,"compression":"","view":{"view_algorithm":0,"view_definer":{"Username":"root","Hostname":"192.168.102.8","CurrentUser":false,"AuthUsername":"root","AuthHostname":"%"},"view_security":0,"view_select":"select * from TRAIN_DIR","view_checkoption":1,"view_cols":[{"O":"START_DATE","L":"start_date"},{"O":"STOP_DATE","L":"stop_date"},{"O":"TRAIN_CODE","L":"train_code"},{"O":"SUBBUREAU_CODE","L":"subbureau_code"},{"O":"DOUBLE_ID","L":"double_id"},{"O":"SCHEMA_ID","L":"schema_id"},{"O":"RUNNING_STYLE","L":"running_style"},{"O":"RUNNING_RULE","L":"running_rule"},{"O":"START_STATION_NAME","L":"start_station_name"},{"O":"END_STATION_NAME","L":"end_station_name"},{"O":"TRAIN_TYPE_CODE","L":"train_type_code"},{"O":"TRAIN_CLASS_CODE","L":"train_class_code"},{"O":"SEAT_TYPES","L":"seat_types"},{"O":"TRAIN_GROUP","L":"train_group"},{"O":"BELONG_LINE1","L":"belong_line1"},{"O":"PRICE_STYLE1","L":"price_style1"},{"O":"BELONG_LINE2","L":"belong_line2"},{"O":"PRICE_STYLE2","L":"price_style2"},{"O":"BELONG_LINE3","L":"belong_line3"},{"O":"PRICE_STYLE3","L":"price_style3"},{"O":"BELONG_LINE4","L":"belong_line4"},{"O":"PRICE_STYLE4","L":"price_style4"},{"O":"BELONG_LINE5","L":"belong_line5"},{"O":"PRICE_STYLE5","L":"price_style5"},{"O":"SERVICE_TYPE","L":"service_type"},{"O":"PRICE_STYLE","L":"price_style"},{"O":"ORIGIN","L":"origin"}]},"Lock":null,"version":3}
> 
> 	at com.pingcap.tikv.catalog.CatalogTransaction.parseFromJson(CatalogTransaction.java:305)
> 	at com.pingcap.tikv.catalog.CatalogTransaction.getTables(CatalogTransaction.java:287)
> 	at com.pingcap.tikv.catalog.Catalog$CatalogCache.loadTables(Catalog.java:100)
> 	at com.pingcap.tikv.catalog.Catalog$CatalogCache.getTable(Catalog.java:94)
> 	at com.pingcap.tikv.catalog.Catalog.getTable(Catalog.java:222)
> 	at com.pingcap.tikv.catalog.Catalog.getTable(Catalog.java:216)

**Comment by zhexuany** [comment]
@ivorzhou Could you also tell the version of TiDB and TiKV you are using? 
It seems like you have view in your schema which leads failure when parsing Json.

**Comment by ivorzhou** [comment]
> @ivorzhou Could you also tell the version of TiDB and TiKV you are using?
> It seems like you have view in your schema which leads failure when parsing Json.

Hi @zhexuany   
TiDB is 3.0.0 beta and Ti spark is master branch.
And I think Tikv client can't parse the view meta info.

**Comment by zhexuany** [comment]
Yes, per exception tract we can tell tike-client cannot parse schema with view. Fixing parsing part is easy, the problem is how to let tispark read schema with view. We are actively investigating this. 

Thanks for reporting. ;)
