### ISSUE TITLE
tispark support authentication to TiKV and PD

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#952]
**Is your feature request related to a problem? Please describe.**
https://stackoverflow.com/questions/57214425/is-pd-component-has-any-authentication-method-to-limit-databases-that-spark-can

![image](https://user-images.githubusercontent.com/5574887/61936431-51f2ed00-afbf-11e9-90d4-0d4aed50ed74.png)

```
a spark cluster with many members doing with data analytic and can see all databases. It makes our stuck
```

currently tispark do not support authentication to TiKV and PD, anyone who knows the PD address can connect to PD using tispark.

**Comment by shiyuhang0** [comment]
closed by https://github.com/pingcap/tispark/pull/2185

**Comment by Dieken** [comment]
@shiyuhang0  看起来要不要认证是 TiSpark 作为客户端决定的，不是 TiKV 决定的，所以只要 TiSpark job 可以修改那几个参数，就能不需要认证、授权就访问 TiKV 所有数据了？
