### ISSUE TITLE
Refactor RegionStoreClient Logic

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#987]
Propose a better design for RegionStoreClient.

1. RegionStoreClient should be inaccessible directly.
2. All apis of RegionStoreClient should not provide retry aside from callWithRetry, if a request needs to be retried because of an un-retryable cause, e.g., keys need to be re-split across regions/stores, region info outdated, e.t.c., we should retry it in an upper client logic (KVClient, TxnClient, e.t.c.)

@marsishandsome @zhexuany PTAL

**Comment by marsishandsome** [comment]
nice & LGTM
